(function () {
  "use strict";
  const D = window.PWA_DATA;
  const L = window.PWA_LOGIC;
  const KEY = "fioreRosaStateV1";
  const defaultState = {done:[], notes:{}, saved:[], last:"home", font:1, contrast:false, answers:{}};
  let state = load();
  let deferredPrompt = null;
  const $ = selector => document.querySelector(selector);
  const main = $("#main");
  const esc = value => String(value ?? "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));

  function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||"{}")};}catch{return {...defaultState};}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state));updateProgress();}
  function toast(message){const el=$("#toast");el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2200);}
  function route(){return (location.hash.slice(1)||"home").split("?")[0];}
  function chapterByRoute(value){const match=/^capitolo-(\d+)$/.exec(value);return match?D.chapters.find(c=>c.n===Number(match[1])):null;}
  function badge(value){return `<span class="certainty ${esc(value)}">${esc(value)}</span>`;}
  function updateProgress(){
    const count=state.done.length;$("#progressLabel").textContent=`${count} di ${D.chapters.length} capitoli`;$("#progressBar").style.width=`${(count/D.chapters.length)*100}%`;
    document.querySelectorAll(".nav-link[data-route^='capitolo-']").forEach(a=>a.classList.toggle("done",state.done.includes(Number(a.dataset.route.split("-")[1]))));
  }
  function buildNav(){
    $("#chapterNav").innerHTML=D.chapters.map(c=>`<a class="nav-link" href="#capitolo-${c.n}" data-route="capitolo-${c.n}"><span>${String(c.n).padStart(2,"0")}</span> ${esc(c.title)}</a>`).join("");
    updateProgress();
  }
  function home(){
    return `<section class="hero">
      <div class="hero-media"><img src="assets/images/hero_rosa_molti_mondi.webp" alt="Una rosa collegata a diversi mondi medievali: giardino, corte, manoscritto e paradiso"></div>
      <div class="hero-content"><span class="eyebrow">Percorso storico · III anno</span><h1>Il fiore e <em>la rosa</em></h1><p class="lead">${esc(D.question)}</p><div class="hero-actions"><a class="primary-button" href="#capitolo-1">Comincia dalla materia</a><button class="secondary-button" data-action="open-map" data-map="rete">Apri la mappa</button></div></div>
      <nav class="context-ring" aria-label="Accesso ai contesti">${D.chapters.slice(0,9).map(c=>`<a href="#capitolo-${c.n}">${esc(c.kicker)}</a>`).join("")}</nav>
    </section>
    <div class="page"><div class="home-grid"><section class="panel"><span class="eyebrow">La tesi di metodo</span><h2>Non un fiore, ma una rete di usi</h2><p>La rosa non porta nel Medioevo un messaggio unico. Diventa segno quando una pratica, un testo o un'immagine ne selezionano una qualità. Questa PWA segue le differenze prima delle somiglianze e segnala ciò che è attestato, probabile o discusso.</p><ul class="method-list"><li><strong>1 · Oggetto</strong>Che cosa compare davvero?</li><li><strong>2 · Contesto</strong>Dove, quando, per chi?</li><li><strong>3 · Funzione</strong>Che cosa fa nel testo?</li><li><strong>4 · Certezza</strong>Quanto regge l'ipotesi?</li></ul></section><aside class="panel"><span class="eyebrow">Strumenti</span><h2>Studia attivamente</h2><p>Annota ogni capitolo, salva citazioni, confronta otto contesti e verifica ciò che sai. I dati restano sul dispositivo.</p><div class="note-actions"><a class="secondary-button" href="#confronto">Tavola comparativa</a><a class="secondary-button" href="#taccuino">Taccuino</a></div></aside></div>
    <section aria-labelledby="chaptersTitle"><span class="eyebrow" style="margin-top:3rem">Dieci passaggi</span><h2 id="chaptersTitle">Dalla pianta alla visione</h2><div class="chapter-list">${D.chapters.map(c=>`<a class="chapter-card" href="#capitolo-${c.n}"><img src="${c.image}" alt=""><div class="chapter-card-content"><small>${String(c.n).padStart(2,"0")} · ${esc(c.kicker)}</small><h3>${esc(c.title)}</h3><span>${esc(c.question)}</span></div></a>`).join("")}</div></section></div>`;
  }
  function quoteCard(chapter){
    if(!chapter.quote)return ""; const saved=state.saved.some(s=>s.id===`q${chapter.n}`);
    return `<figure class="quote-card"><blockquote>«${esc(chapter.quote.text)}»</blockquote><cite>${esc(chapter.quote.cite)}</cite><details class="translation"><summary>Traduzione di servizio</summary><p>${esc(chapter.quote.translation)}</p></details><button class="secondary-button" data-action="save-quote" data-id="q${chapter.n}" data-chapter="${chapter.n}">${saved?"Citazione salvata ✓":"Salva nel taccuino"}</button></figure>`;
  }
  function quizCard(chapter){const q=chapter.quiz;return `<section class="quiz-box"><span class="eyebrow">Controllo rapido</span><h3>${esc(q.q)}</h3><div class="quiz-options">${q.options.map((o,i)=>`<button class="quiz-option" data-action="chapter-answer" data-answer="${L.letter(i)}" data-chapter="${chapter.n}"><strong>${L.letter(i)}</strong> ${esc(o)}</button>`).join("")}</div><div class="feedback" id="feedback-${chapter.n}" hidden></div></section>`;}
  function chapterPage(c){
    state.last=`capitolo-${c.n}`;save(); const next=c.n<D.chapters.length?`#capitolo-${c.n+1}`:"#confronto"; const prev=c.n>1?`#capitolo-${c.n-1}`:"#home";
    return `<header class="chapter-head"><div class="chapter-head-copy"><span class="eyebrow">${String(c.n).padStart(2,"0")} · ${esc(c.kicker)}</span><h1>${esc(c.title)}</h1><p class="question">${esc(c.question)}</p>${badge(c.certainty)}</div><div class="chapter-head-media"><img src="${c.image}" alt="${esc(c.imageAlt)}"><span class="media-label">${esc(c.imageLabel)}</span></div></header>
    <article class="page"><div class="chapter-layout"><div>${c.sections.map(s=>`<section class="article-section"><h2>${esc(s[0])}</h2>${s[1].map(p=>`<p>${esc(p)}</p>`).join("")}</section>`).join("")}${quoteCard(c)}<section class="activity"><span class="eyebrow">Laboratorio</span><h3>Metti alla prova il metodo</h3><p>${esc(c.activity)}</p></section>${quizCard(c)}</div>
    <aside class="side-stack"><section class="essentials"><h3>Da non perdere</h3><ul>${c.essentials.map(e=>`<li>${esc(e)}</li>`).join("")}</ul></section><section class="source-note"><strong>Stato delle fonti</strong><p>${esc(c.sourceNote)}</p></section></aside></div>
    <section><span class="eyebrow" style="margin-top:3rem">Lessico</span><h2>Tre parole per orientarsi</h2><dl class="glossary">${c.glossary.map(g=>`<div class="term"><dt>${esc(g[0])}</dt><dd>${esc(g[1])}</dd></div>`).join("")}</dl></section>
    <section class="panel note-box" style="margin-top:2rem"><span class="eyebrow">Taccuino personale</span><h2>La tua nota</h2><textarea id="chapterNote" data-chapter="${c.n}" placeholder="Scrivi un'osservazione, un dubbio o un collegamento...">${esc(state.notes[c.n]||"")}</textarea><div class="note-actions"><button class="primary-button" data-action="save-note" data-chapter="${c.n}">Salva nota</button><button class="secondary-button" data-action="print">Stampa capitolo</button></div></section>
    <nav class="chapter-actions" aria-label="Navigazione fra capitoli"><a class="secondary-button" href="${prev}">← Precedente</a><button class="primary-button" data-action="complete" data-chapter="${c.n}">${state.done.includes(c.n)?"Completato ✓":"Segna come completato"}</button><a class="secondary-button" href="${next}">Successivo →</a></nav></article>`;
  }
  function comparison(){return `<div class="page"><span class="eyebrow">Sinossi</span><h1>La stessa forma, funzioni diverse</h1><p class="lead">La tavola non cerca un minimo comune denominatore. Mette in evidenza che supporto, genere, attori e pubblico modificano il valore del fiore.</p><div class="comparison-wrap"><table><thead><tr><th>Contesto</th><th>Forma</th><th>Funzione</th><th>Genere</th><th>Pubblico</th><th>Certezza</th></tr></thead><tbody>${D.contexts.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table></div><section style="margin-top:2rem"><span class="eyebrow">Mappe concettuali</span><div class="map-preview"><article class="map-card"><img src="assets/maps/rete_significati.svg" alt="Mappa della rete dei significati della rosa"><div><h3>Rete dei significati</h3><p>Dalla materia ai diversi contesti.</p><button class="secondary-button" data-action="open-map" data-map="rete">Ingrandisci</button></div></article><article class="map-card"><img src="assets/maps/sintesi_contesti.svg" alt="Mappa di sintesi dei contesti medievali della rosa"><div><h3>Sintesi dei contesti</h3><p>Fonti, generi, funzioni e cautele.</p><button class="secondary-button" data-action="open-map" data-map="sintesi">Ingrandisci</button></div></article></div></section></div>`;}
  function verification(){return `<div class="page"><span class="eyebrow">15 domande</span><h1>Verifica finale con recupero</h1><p>Rispondi a tutte le domande. Ogni errore mostra subito il nodo da riprendere; puoi cambiare risposta e ritentare.</p><div class="final-grid">${D.finalQuiz.map((q,qi)=>`<section class="final-question" data-q="${qi}"><h3>${qi+1}. ${esc(q.q)}</h3><div class="quiz-options">${q.o.map((o,i)=>`<button class="quiz-option ${state.answers[qi]===L.letter(i)?"selected":""}" data-action="final-answer" data-q="${qi}" data-answer="${L.letter(i)}"><strong>${L.letter(i)}</strong> ${esc(o)}</button>`).join("")}</div><div class="feedback" hidden></div></section>`).join("")}</div><div class="final-results"><div><span class="eyebrow" style="color:#e9c77d">Risultato</span><strong id="scoreLabel">${score()} / ${D.finalQuiz.length}</strong></div><span id="scoreText">${Object.keys(state.answers).length} risposte registrate</span><button class="primary-button" data-action="grade-final">Correggi tutto</button></div></div>`;}
  function score(){return D.finalQuiz.reduce((n,q,i)=>n+(state.answers[i]===q.c?1:0),0);}
  function notebook(){const notes=Object.entries(state.notes).filter(([,v])=>v.trim());return `<div class="page"><span class="eyebrow">Il tuo lavoro</span><h1>Taccuino</h1><p>Note e citazioni sono conservate soltanto in questo browser. Puoi esportarle come file di testo.</p><div class="note-actions"><button class="primary-button" data-action="export">Esporta .txt</button><button class="secondary-button" data-action="print">Stampa</button></div><h2>Note</h2><div class="notebook-grid">${notes.length?notes.map(([n,v])=>`<article class="notebook-item"><small>Capitolo ${n} · ${esc(D.chapters[n-1].title)}</small><p>${esc(v)}</p><a href="#capitolo-${n}">Torna al capitolo</a></article>`).join(""):`<p class="empty-state">Non hai ancora scritto note.</p>`}</div><h2>Citazioni salvate</h2><div class="notebook-grid">${state.saved.length?state.saved.map(s=>`<article class="notebook-item"><blockquote>«${esc(s.text)}»</blockquote><small>${esc(s.cite)}</small></article>`).join(""):`<p class="empty-state">Non hai ancora salvato citazioni.</p>`}</div></div>`;}
  function sources(){return `<div class="page"><span class="eyebrow">Bibliografia ragionata</span><h1>Fonti e strumenti</h1><p>Le schede privilegiano testi primari digitalizzati, istituzioni culturali e repertori scientifici. Le immagini generate sono sempre indicate come ricostruzioni.</p><div class="source-grid">${D.sources.map(s=>`<a class="source-card" href="${s[2]}" target="_blank" rel="noopener"><strong>${esc(s[0])} ↗</strong><span>${esc(s[1])}</span></a>`).join("")}</div><p style="margin-top:2rem"><a href="ATTRIBUTIONS.md">Attribuzioni delle immagini</a> · <a href="README.md">Nota didattica e tecnica</a></p></div>`;}
  function render(){
    if($("#searchDialog").open)$("#searchDialog").close();
    const r=route();const c=chapterByRoute(r);main.innerHTML=c?chapterPage(c):r==="confronto"?comparison():r==="verifica"?verification():r==="taccuino"?notebook():r==="fonti"?sources():home();
    document.querySelectorAll(".nav-link").forEach(a=>a.classList.toggle("active",a.dataset.route===r));main.focus({preventScroll:true});window.scrollTo(0,0);closeMenu();
  }
  function complete(n){if(!state.done.includes(n))state.done.push(n);save();render();toast("Capitolo completato");}
  function saveNote(n){state.notes[n]=$("#chapterNote").value;save();toast("Nota salvata nel taccuino");}
  function saveQuote(n){const c=D.chapters[n-1];if(!c.quote)return;const id=`q${n}`;if(state.saved.some(s=>s.id===id)){state.saved=state.saved.filter(s=>s.id!==id);toast("Citazione rimossa");}else{state.saved.push({id,text:c.quote.text,cite:c.quote.cite});toast("Citazione salvata");}save();render();}
  function chapterAnswer(n,answer,button){const c=D.chapters[n-1],ok=L.grade(answer,c.quiz.correct),box=button.closest(".quiz-box"),feedback=box.querySelector(".feedback");box.querySelectorAll(".quiz-option").forEach(b=>{b.classList.remove("correct","wrong");if(b.dataset.answer===c.quiz.correct)b.classList.add("correct");});if(!ok)button.classList.add("wrong");feedback.hidden=false;feedback.innerHTML=`<strong>${ok?"Corretto.":"Da rivedere."}</strong> ${esc(c.quiz.feedback)}${ok?"":`<br><em>Recupero: ${esc(c.quiz.recovery)}</em>`}`;}
  function finalAnswer(q,a){state.answers[q]=a;save();render();document.querySelector(`[data-q="${q}"]`)?.scrollIntoView({block:"center"});}
  function gradeFinal(){document.querySelectorAll(".final-question").forEach((el,i)=>{const q=D.finalQuiz[i],a=state.answers[i],fb=el.querySelector(".feedback");el.querySelectorAll(".quiz-option").forEach(b=>{b.classList.remove("correct","wrong");if(b.dataset.answer===q.c)b.classList.add("correct");if(a===b.dataset.answer&&a!==q.c)b.classList.add("wrong");});fb.hidden=false;fb.innerHTML=a?`<strong>${a===q.c?"Corretto.":"Da recuperare."}</strong> ${esc(q.f)}`:"<strong>Non risposta.</strong> Torna alla domanda e scegli un'opzione.";});$("#scoreLabel").textContent=`${score()} / ${D.finalQuiz.length}`;$("#scoreText").textContent=`${L.percent(score(),D.finalQuiz.length)}% · ${score()>=12?"Padronanza raggiunta":"Riprendi i feedback e ritenta"}`;}
  function openMap(kind){const info=kind==="sintesi"?{title:"Sintesi dei contesti",src:"assets/maps/sintesi_contesti.svg",alt:"Mappa che collega fonte, genere, funzione, pubblico e grado di certezza nei contesti della rosa medievale.",desc:"Al centro è la rosa in contesto. I rami distinguono materia, Scrittura e devozione, corte e allegoria, visione dantesca. Ogni ramo richiede fonte, genere, funzione e certezza."}:{title:"Rete dei significati",src:"assets/maps/rete_significati.svg",alt:"Mappa dalla rosa materiale alle funzioni mediche, bibliche, mariane, cortesi, allegoriche e teologiche.",desc:"La rosa materiale offre colore, profumo, spine e caducità. Pratiche e generi selezionano proprietà diverse: cura, esegesi, devozione, desiderio, comicità, allegoria e comunità dei beati."};$("#mapDialogTitle").textContent=info.title;$("#mapDialogImage").src=info.src;$("#mapDialogImage").alt=info.alt;$("#mapDialogDescription").textContent=info.desc;$("#mapDialog").showModal();}
  function exportNotes(){let out=`${D.title}\nEsportazione del taccuino\n\n`;Object.entries(state.notes).filter(([,v])=>v.trim()).forEach(([n,v])=>out+=`CAPITOLO ${n} · ${D.chapters[n-1].title}\n${v}\n\n`);state.saved.forEach(s=>out+=`CITAZIONE\n“${s.text}”\n${s.cite}\n\n`);const blob=new Blob([out],{type:"text/plain;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="taccuino-fiore-rosa.txt";a.click();URL.revokeObjectURL(a.href);}
  function search(value){const q=L.normalize(value.trim());const box=$("#searchResults");if(q.length<2){box.innerHTML="<p>Scrivi almeno due caratteri.</p>";return;}const hits=[];D.chapters.forEach(c=>{const hay=L.normalize([c.title,c.question,...c.sections.flat(2),...c.glossary.flat()].join(" "));if(hay.includes(q))hits.push(c);});box.innerHTML=hits.length?hits.map(c=>`<a class="search-result" href="#capitolo-${c.n}"><strong>${c.n}. ${esc(c.title)}</strong><br><small>${esc(c.question)}</small></a>`).join(""):"<p>Nessun risultato. Prova una parola più breve.</p>";}
  function openMenu(){$("#sidebar").classList.add("open");$("#scrim").hidden=false;$("#menuButton").setAttribute("aria-expanded","true");}
  function closeMenu(){$("#sidebar").classList.remove("open");$("#scrim").hidden=true;$("#menuButton").setAttribute("aria-expanded","false");}
  function applySettings(){document.documentElement.style.setProperty("--font-scale",state.font);document.body.classList.toggle("high-contrast",state.contrast);$("#contrastToggle").checked=state.contrast;document.querySelectorAll("[data-scale]").forEach(b=>b.classList.toggle("active",Number(b.dataset.scale)===Number(state.font)));}
  document.addEventListener("click",event=>{const b=event.target.closest("[data-action]");if(!b)return;const a=b.dataset.action;if(a==="complete")complete(Number(b.dataset.chapter));if(a==="save-note")saveNote(Number(b.dataset.chapter));if(a==="save-quote")saveQuote(Number(b.dataset.chapter));if(a==="chapter-answer")chapterAnswer(Number(b.dataset.chapter),b.dataset.answer,b);if(a==="final-answer")finalAnswer(Number(b.dataset.q),b.dataset.answer);if(a==="grade-final")gradeFinal();if(a==="open-map")openMap(b.dataset.map);if(a==="export")exportNotes();if(a==="print")window.print();});
  $("#menuButton").addEventListener("click",()=>$("#sidebar").classList.contains("open")?closeMenu():openMenu());$("#scrim").addEventListener("click",closeMenu);
  $("#searchButton").addEventListener("click",()=>{$("#searchDialog").showModal();$("#searchInput").focus();});$("#searchInput").addEventListener("input",e=>search(e.target.value));
  $("#settingsButton").addEventListener("click",()=>$("#settingsDialog").showModal());$("#installButton").addEventListener("click",async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;}else $("#installDialog").showModal();});
  $("#resumeButton").addEventListener("click",()=>location.hash=`#${state.last||"capitolo-1"}`);$("#contrastToggle").addEventListener("change",e=>{state.contrast=e.target.checked;save();applySettings();});
  $("#fontScaleControls").addEventListener("click",e=>{const b=e.target.closest("[data-scale]");if(!b)return;state.font=Number(b.dataset.scale);save();applySettings();});
  $("#resetButton").addEventListener("click",()=>{if(confirm("Vuoi cancellare note, citazioni e progressi salvati su questo dispositivo?")){state={...defaultState,notes:{},saved:[],done:[],answers:{}};save();applySettings();$("#settingsDialog").close();render();}});
  window.addEventListener("hashchange",render);window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;});window.addEventListener("online",()=>$("#networkStatus").hidden=true);window.addEventListener("offline",()=>$("#networkStatus").hidden=false);
  if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
  buildNav();applySettings();render();
}());
