'use strict';
var KEY='gbprof-boccaccio-v1';
var state={read:[],quiz:null};
try{var saved=JSON.parse(localStorage.getItem(KEY)||'{}');state.read=saved.read||[];state.quiz=saved.quiz||null;}catch(e){}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
var main=document.getElementById('main');

var sections=[
{id:'terra',title:'Boccaccio scende sulla terra',sub:'Da Dante e Petrarca alla varietà del reale',body:"<p class='kicker'>Tappa 1</p><h1>Boccaccio scende sulla terra</h1><p class='muted'>La formula della tua vecchia lezione resta potente, ma va precisata: Boccaccio non abbandona la fede; cambia soprattutto il centro della rappresentazione.</p><h3>Tre modi di guardare l’uomo</h3><div class='split'><div class='pole old'><strong>Dante</strong><p>La realtà è ordinata dentro un significato complessivo, morale e teologico.</p></div><div class='pole new'><strong>Petrarca</strong><p>Il mondo passa attraverso il conflitto dell’io, della memoria e del desiderio.</p></div></div><div class='quote'>Con Boccaccio la realtà torna ad allargarsi: non per essere ordinata dall’alto, ma per essere osservata nella sua varietà.</div><p>Mercanti, nobili, frati, donne, servi, giudici, avventurieri: nel <em>Decameron</em> entrano in scena persone diversissime, spinte da desiderio, interesse, paura, amore, ambizione, fortuna e ingegno.</p>"},
{id:'cornice',title:'La peste e la cornice',sub:'Dal caos del 1348 a una comunità che ricostruisce ordine',body:"<p class='kicker'>Tappa 2</p><h1>La peste e la cornice</h1><p>Il <em>Decameron</em> si apre con la peste del 1348. La malattia distrugge non solo i corpi, ma anche legami, regole e abitudini sociali. La brigata dei sette giovani donne e tre giovani uomini si allontana da Firenze e costruisce temporaneamente un altro modo di vivere.</p><h3>Fuggire non significa negare la realtà</h3><p>La villa non è un paradiso astratto. È un laboratorio di civiltà: turni, regole, temi, musica, racconto. Contro il disordine della peste, la brigata oppone una forma condivisa.</p><div class='timeline'><div class='time-row'><strong>Firenze</strong><span>peste, rottura delle consuetudini, paura</span></div><div class='time-row'><strong>Villa</strong><span>ordine scelto, convivenza, parola</span></div><div class='time-row'><strong>Racconto</strong><span>trasformare l’esperienza in forma e conoscenza</span></div><div class='time-row'><strong>Ritorno</strong><span>la sospensione finisce: il mondo reale resta</span></div></div>"},
{id:'forze',title:'Natura, Fortuna, Industria',sub:'Tre forze che muovono il mondo del Decameron',body:"<p class='kicker'>Tappa 3</p><h1>Natura, Fortuna, Industria</h1><p>Una delle chiavi più efficaci per leggere Boccaccio è osservare tre forze che continuamente si intrecciano.</p><div class='triad'><div class='force natura'><h3>Natura</h3><p>Il desiderio, il corpo, l’amore, l’istinto di vita. Ciò che appartiene all’essere umano e che non può essere cancellato con un divieto.</p></div><div class='force fortuna'><h3>Fortuna</h3><p>L’imprevisto, il caso, il rovescio, il naufragio, l’incontro. Ciò che l’uomo non controlla.</p></div><div class='force industria'><h3>Industria</h3><p>Ingegno, parola, esperienza, capacità di adattarsi. La risposta umana all’imprevisto.</p></div></div><div class='quote'>Il Decameron non promette che l’intelligenza vinca sempre. Mostra però che vivere significa misurarsi continuamente con ciò che accade.</div>"},
{id:'amore',title:'L’amore è natura',sub:'Dal codice cortese alla concretezza del desiderio',body:"<p class='kicker'>Tappa 4</p><h1>L’amore è natura</h1><p>Nel materiale originario insistevi sul superamento dell’amore cortese. L’intuizione funziona se non la trasformiamo in una cesura assoluta: Boccaccio conserva molti valori cortesi, ma li mette alla prova dentro una società concreta.</p><h3>Che cosa cambia?</h3><p>L’amore non è soltanto ascesa spirituale né soltanto errore da giudicare a posteriori. È una forza naturale che può rendere felici, far soffrire, spingere all’azione, produrre inganno o generosità.</p><div class='split'><div class='pole old'><strong>Eredità cortese</strong><p>gentilezza, nobiltà d’animo, servizio amoroso, liberalità.</p></div><div class='pole new'><strong>Mondo nuovo</strong><p>corpo, scelta, reciprocità, astuzia, matrimonio, interessi sociali.</p></div></div><p>Proprio <em>Federigo degli Alberighi</em> mostra questa trasformazione: il vecchio codice cortese non viene semplicemente distrutto, ma ricollocato dentro il nuovo mondo mercantile.</p>"},
{id:'fiammetta',title:'Fiammetta e la voce femminile',sub:'Dalla donna cantata alla donna che parla',body:"<p class='kicker'>Tappa 5</p><h1>Fiammetta: una donna prende la parola</h1><p>Nel tuo approfondimento Fiammetta diventa il punto di passaggio fra Beatrice, Laura e una figura femminile più terrena. È una direzione didattica molto fertile, purché non trasformiamo le tre donne in simboli rigidi.</p><h3>Nell’Elegia</h3><p>Fiammetta racconta in prima persona il proprio abbandono amoroso. Non è solo oggetto dello sguardo maschile: diventa soggetto della narrazione, osserva i propri sentimenti, li interpreta e li mette in parola.</p><h3>Nel Decameron</h3><p>Fiammetta è una delle narratrici della brigata. Racconta storie in cui desiderio, dolore, intelligenza e fortuna mettono continuamente alla prova donne e uomini.</p><div class='quote'>Il salto decisivo non è “donna ideale contro donna reale”: è la crescita dello spazio concesso alla voce, all’azione e alla scelta femminile.</div>"},
{id:'federigo',title:'Federigo degli Alberighi',sub:'Vecchio e nuovo nello stesso racconto',body:"<p class='kicker'>Tappa 6</p><h1>Federigo degli Alberighi</h1><p>Questa novella, già al centro delle tue lezioni, è perfetta per vedere Boccaccio mentre fa incontrare due sistemi di valori.</p><h3>Federigo</h3><p>È «in cortesia pregiato»: sperpera il patrimonio per amore, resta generoso anche da povero e sacrifica il falcone per onorare Giovanna. Il gesto cortese raggiunge qui il suo punto estremo e paradossale.</p><h3>Giovanna</h3><p>Non rimane una figura immobile. È donna amata, madre che agisce per il figlio, vedova sottoposta alle pressioni familiari e infine persona che sceglie Federigo.</p><h3>Il falcone</h3><p>È insieme ultimo bene economico, simbolo aristocratico e oggetto d’amore. La sua distruzione permette alla novella di trasformare una perdita in riconoscimento morale.</p><div class='split'><div class='pole old'><strong>Società cortese</strong><p>servizio d’amore, magnificenza, nobiltà del gesto.</p></div><div class='pole new'><strong>Società mercantile</strong><p>patrimonio, utilità, scelta matrimoniale, equilibrio fra valore e ricchezza.</p></div></div>"},
{id:'giletta',title:'Giletta di Narbona',sub:'Volontà, competenza e strategia',body:"<p class='kicker'>Tappa 7</p><h1>Giletta di Narbona</h1><p>Il dialogo che hai costruito con Giletta contiene una domanda filosofica molto interessante: la passione è la forza motrice e l’intelligenza è lo strumento con cui l’essere umano prova a darle forma?</p><h3>Che cosa fa Giletta?</h3><p>Usa la competenza medica ereditata dal padre, guarisce il re, ottiene Beltramo come marito e affronta condizioni quasi impossibili ricorrendo a una strategia complessa.</p><h3>Non è un’eroina moderna</h3><p>Leggerla come simbolo puro di emancipazione sarebbe anacronistico. Ma è indubbio che Boccaccio le attribuisca iniziativa, sapere, perseveranza e capacità di modificare la propria posizione sociale.</p><div class='dialogue'><strong>Domanda da portare in classe:</strong> fino a che punto l’industria di Giletta è libertà, e da quale punto diventa manipolazione?</div>"},
{id:'molteplicita',title:'Il mondo in cento storie',sub:'Realismo, pluralità e assenza di una voce unica',body:"<p class='kicker'>Tappa 8</p><h1>Il mondo in cento storie</h1><p>Nel <em>Decameron</em> non esiste un solo protagonista e non c’è un’unica prospettiva capace di esaurire la realtà. Le cento novelle funzionano come cento esperimenti sul comportamento umano.</p><h3>Realismo?</h3><p>Non significa fotografia neutra della società. Significa attenzione a luoghi, mestieri, denaro, mobilità sociale, linguaggi, interessi e conseguenze concrete delle azioni.</p><h3>La voce dell’autore</h3><p>Boccaccio costruisce una macchina narrativa in cui raccontano dieci giovani e, dentro le novelle, parlano decine di personaggi. La sua regia è fortissima, ma lascia emergere una pluralità di valori e punti di vista.</p><div class='quote'>Dante cerca un ordine del mondo. Petrarca interroga l’io. Boccaccio mette il mondo in movimento e lo lascia parlare attraverso cento storie.</div>"}
];

var women=[
{name:'Ghismunda',tag:'IV, 1',desc:'Ama Guiscardo contro il volere del padre Tancredi. Difende con lucidità il proprio desiderio e paga con la vita il conflitto fra scelta personale e potere familiare.'},
{name:'Madonna Filippa',tag:'VI, 7',desc:'Trasforma un processo per adulterio in una prova di eloquenza. La parola diventa strumento di difesa e di modifica della legge.'},
{name:'Giletta di Narbona',tag:'III, 9',desc:'Competenza medica, perseveranza e strategia: agisce dentro i vincoli sociali invece di limitarsi a subirli.'},
{name:'Zinevra',tag:'II, 9',desc:'Accusata ingiustamente, si salva, cambia identità, costruisce la prova e smaschera chi l’ha calunniata.'},
{name:'Bartolomea',tag:'II, 10',desc:'Rifiuta di tornare a un matrimonio che considera privo di vita e sceglie una relazione diversa. Una figura volutamente provocatoria.'},
{name:'Alatiel',tag:'II, 7',desc:'La fortuna la trascina attraverso il Mediterraneo. La sua storia mette in crisi il rapporto fra esperienza reale e reputazione sociale.'},
{name:'Monna Giovanna',tag:'V, 9',desc:'Passa da donna corteggiata a madre agente e infine a vedova che sceglie Federigo, pur dentro le regole familiari del tempo.'},
{name:'Fiammetta',tag:'brigata',desc:'Narratrice e figura ricorrente nell’opera boccacciana: collega esperienza amorosa, parola femminile e consapevolezza narrativa.'}
];

var days=[
['1','tema libero','Ciappelletto, Abraam, Melchisedech: religione, parola, intelligenza.'],
['2','fortuna','Chi, dopo molte traversie, giunge a lieto fine.'],
['3','industria','Chi ottiene ciò che desidera grazie all’ingegno.'],
['4','amori infelici','Desiderio e tragedia; Ghismunda è uno dei vertici.'],
['5','amori felici','Dopo prove e ostacoli, l’amore giunge a buon fine.'],
['6','motti','La parola pronta salva, corregge, rovescia i rapporti di forza.'],
['7','beffe coniugali','Mogli e mariti dentro una comicità spesso spregiudicata.'],
['8','beffe','L’astuzia diventa motore del racconto.'],
['9','tema libero','Ritorna la varietà senza un argomento unico.'],
['10','liberalità','Virtù, magnificenza, prove morali e sociali.']
];

function mapCore(){
return "<div class='map'><div class='map-lines'></div><div class='node n1'><strong>Natura</strong>desiderio, corpo, impulso vitale</div><div class='node n2'><strong>Fortuna</strong>caso, rovescio, incontro, perdita</div><div class='node n3'><strong>Industria</strong>ingegno, parola, esperienza</div><div class='node n4'><strong>Società</strong>denaro, status, regole, reputazione</div><div class='map-center'>Decameron<br><small>vita in movimento</small></div></div>";
}
function sources(){
return "<section class='panel sources'><h3>Materiali e immagine</h3><p>Percorso rielaborato dai materiali di gbprof nella cartella Boccaccio: lezione storica, versione completa, approfondimento su Fiammetta, analisi delle donne del Decameron e conversazione didattica su Giletta di Narbona.</p><p>Ritratto: Andrea del Castagno, <em>Giovanni Boccaccio</em>, circa 1450, ciclo degli Uomini illustri, pubblico dominio; immagine da Wikimedia Commons.</p></section>";
}
function home(){
var pct=Math.round(state.read.length/sections.length*100);
var cards=sections.map(function(s,i){return "<a class='lesson' href='#"+s.id+"'><span class='n'>0"+(i+1)+"</span><h3>"+s.title+"</h3><p>"+s.sub+"</p></a>";}).join('');
main.innerHTML="<section class='hero'><div class='hero-copy'><span class='chip'>Letteratura · III anno</span><p class='eyebrow'>Giovanni Boccaccio</p><h1>Il mondo<br>in cento storie</h1><p class='lead'>Natura, Fortuna, Industria. La letteratura esce dal simbolo e incontra persone, corpi, denaro, desideri e intelligenze.</p><div class='cta'><a class='button' href='#terra'>Inizia il percorso</a><a class='button secondary' href='#mappe'>Apri le mappe</a></div></div><div class='hero-visual'><figure class='portrait-frame'><img src='https://upload.wikimedia.org/wikipedia/commons/2/29/Andrea_del_Castagno_Giovanni_Boccaccio_c_1450.jpg' alt='Ritratto di Giovanni Boccaccio dipinto da Andrea del Castagno circa nel 1450'><figcaption>Andrea del Castagno · Giovanni Boccaccio · circa 1450</figcaption></figure></div></section><div class='wrap'><section class='intro'><div class='panel'><p class='kicker'>La tesi</p><h2>Non un uomo solo: una società intera.</h2><p>Se Petrarca restringe il fuoco sulla coscienza, Boccaccio lo riapre sulla varietà del comportamento umano.</p></div><div class='panel'><p class='kicker'>Il tuo percorso</p><h2>"+state.read.length+"/"+sections.length+" tappe completate</h2><div class='progress'><span style='width:"+pct+"%'></span></div><p class='muted'>Il progresso resta salvato su questo dispositivo.</p></div></section><section class='section'><div class='section-head'><p class='kicker'>Percorso</p><h2>Otto tappe dentro il laboratorio umano del Decameron</h2></div><div class='route'>"+cards+"</div></section><section class='section'><div class='section-head'><p class='kicker'>Mappa generale</p><h2>Quattro forze fanno muovere le novelle</h2></div>"+mapCore()+"</section>"+sources()+"</div>";
}
function lesson(s){
main.innerHTML="<div class='wrap'><div class='content-grid'><article class='article'>"+s.body+"<div class='cta'><a class='button' href='#home'>← Indice</a><a class='button' href='#mappe'>Mappe</a></div></article><aside class='aside'><div class='panel'><p class='kicker'>Tappa</p><h3>"+s.title+"</h3><p>"+s.sub+"</p><button id='mark'>"+(state.read.indexOf(s.id)>=0?"✓ Completata":"Segna come completata")+"</button></div><div class='panel'><strong>Domanda chiave</strong><p>Quale forza muove qui i personaggi: Natura, Fortuna, Industria o pressione sociale?</p></div></aside></div></div>";
document.getElementById('mark').onclick=function(){var i=state.read.indexOf(s.id);if(i>=0)state.read.splice(i,1);else state.read.push(s.id);save();lesson(s);};
}
function showDays(){
var cards=days.map(function(d){return "<div class='day'><b>"+d[0]+"ª</b><strong>"+d[1]+"</strong><p>"+d[2]+"</p></div>";}).join('');
main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Architettura</p><h2>Dieci giornate, cento novelle</h2><p>La struttura non elimina la varietà: la organizza. Ogni giornata crea una lente diversa sul comportamento umano.</p></section><div class='days'>"+cards+"</div><section class='section'><div class='panel'><h2>La cornice in cinque passaggi</h2><div class='timeline'><div class='time-row'><strong>1348</strong><span>la peste rompe il tessuto civile di Firenze</span></div><div class='time-row'><strong>Brigata</strong><span>sette donne e tre uomini scelgono di allontanarsi</span></div><div class='time-row'><strong>Regole</strong><span>ogni giorno un re o una regina assegna il tema</span></div><div class='time-row'><strong>100 novelle</strong><span>la realtà viene esplorata da prospettive differenti</span></div><div class='time-row'><strong>Ritorno</strong><span>la comunità temporanea si scioglie e si torna a Firenze</span></div></div></div></section></div>";
}
function showWomen(){
var cards=women.map(function(w){return "<article class='story-card'><span class='tag'>"+w.tag+"</span><h3>"+w.name+"</h3><p>"+w.desc+"</p></article>";}).join('');
main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Atlante delle donne</p><h2>Non esiste «la donna» di Boccaccio</h2><p>Nel materiale che hai raccolto emerge una cosa importante: le figure femminili non formano un modello unico. Alcune agiscono, altre subiscono; alcune parlano, altre tacciono; alcune sfidano le regole, altre le usano a proprio vantaggio.</p></section><div class='women-grid'>"+cards+"</div><section class='section'><div class='panel'><h2>Una domanda più utile di «Boccaccio è moderno?»</h2><p>Quali spazi di azione concede alle sue donne, e quali limiti sociali continuano a determinarle? Questa domanda evita sia di trasformarlo in un femminista ante litteram, sia di ridurre le protagoniste a semplici stereotipi medievali.</p></div></section></div>";
}
function showMaps(){
main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Mappe concettuali</p><h2>Vedere come si muove il mondo boccacciano</h2></section>"+mapCore()+"<section class='section'><div class='concept'><div class='panel'><span class='big'>Dante</span><h3>ordine</h3><p>molteplicità → giudizio → significato complessivo</p></div><div class='panel'><span class='big'>Petrarca</span><h3>coscienza</h3><p>esperienza → memoria → conflitto dell’io</p></div><div class='panel'><span class='big'>Boccaccio</span><h3>società</h3><p>personaggi → azioni → conseguenze → pluralità</p></div></div></section><section class='section'><div class='panel'><h2>Federigo: trasformazione dei valori</h2><div class='timeline'><div class='time-row'><strong>Amore cortese</strong><span>Federigo serve Giovanna e dilapida il patrimonio</span></div><div class='time-row'><strong>Povertà</strong><span>resta la cortesia, scompare la ricchezza</span></div><div class='time-row'><strong>Falcone</strong><span>il gesto generoso distrugge proprio ciò che Giovanna cercava</span></div><div class='time-row'><strong>Scelta</strong><span>Giovanna riconosce il valore dell’uomo</span></div><div class='time-row'><strong>Sintesi</strong><span>nobiltà d’animo e patrimonio tornano a convivere</span></div></div></div></section><section class='section'><div class='panel'><h2>Le donne: da oggetto a soggetto?</h2><div class='timeline'><div class='time-row'><strong>Parola</strong><span>Filippa difende se stessa; Fiammetta racconta; la marchesa risponde al re</span></div><div class='time-row'><strong>Azione</strong><span>Giletta costruisce una strategia; Zinevra salva la propria vita</span></div><div class='time-row'><strong>Desiderio</strong><span>Ghismunda e Bartolomea dichiarano ciò che vogliono</span></div><div class='time-row'><strong>Limite</strong><span>famiglia, reputazione, matrimonio e gerarchie restano vincoli fortissimi</span></div></div></div></section></div>";
}
var questions=[
["Quale triade aiuta a leggere il movimento delle novelle?",["Fede, memoria, gloria","Natura, Fortuna, Industria","Purgatorio, Inferno, Paradiso"],1],
["Che funzione ha la cornice della peste?",["Elimina il rapporto con la realtà","Crea una comunità regolata che risponde al caos con il racconto","Serve solo a spiegare perché le novelle sono cento"],1],
["Che cosa indica soprattutto l’industria?",["La produzione economica moderna","L’ingegno pratico con cui si affrontano gli eventi","La nobiltà ereditaria"],1],
["Come va letto Federigo degli Alberighi?",["Come semplice condanna dell’amore cortese","Come incontro e trasformazione fra valori cortesi e società nuova","Come rifiuto assoluto del denaro"],1],
["Perché Fiammetta è importante nel percorso?",["Perché sostituisce storicamente Beatrice","Perché amplia lo spazio della voce e dell’esperienza femminile","Perché non prova mai dolore"],1],
["Qual è il rischio nel definire Giletta un’eroina moderna?",["Confondere un personaggio trecentesco con categorie contemporanee","Dimenticare che sa curare il re","Non ricordare il suo nome"],0],
["Che cosa significa realismo in questa PWA?",["Fotografia oggettiva e neutrale della società","Attenzione a luoghi, denaro, mestieri, interessi e conseguenze concrete","Assenza di invenzione narrativa"],1],
["Qual è la differenza sintetica proposta fra Petrarca e Boccaccio?",["Petrarca concentra sull’io, Boccaccio riapre sulla pluralità sociale","Petrarca è religioso, Boccaccio ateo","Petrarca scrive poesia, Boccaccio solo storia"],0]
];
function showQuiz(){
var html=questions.map(function(q,i){var opts=q[1].map(function(o,j){return "<label class='option'><input type='radio' name='q"+i+"' value='"+j+"' required> "+o+"</label>";}).join('');return "<fieldset><legend>"+(i+1)+". "+q[0]+"</legend>"+opts+"</fieldset>";}).join('');
main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Verifica</p><h2>Hai capito come funziona il mondo del Decameron?</h2></section><form id='quiz' class='panel quiz'>"+html+"<button>Correggi</button></form><div id='out'></div></div>";
document.getElementById('quiz').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),c=0;questions.forEach(function(q,i){if(Number(f.get('q'+i))===q[2])c++;});state.quiz={score:c,date:new Date().toISOString()};save();var msg=c===8?"Hai colto tutti i nessi principali.":c>=5?"La struttura è compresa; ripassa i passaggi meno sicuri.":"Torna alle mappe: prima dei dettagli servono le forze che muovono le novelle.";document.getElementById('out').innerHTML="<div class='result'><h3>"+c+"/8</h3><p>"+msg+"</p></div>";};
}
function nav(){
var id=location.hash.slice(1)||'home';
if(id==='home')home();
else if(id==='giornate')showDays();
else if(id==='donne')showWomen();
else if(id==='mappe')showMaps();
else if(id==='verifica')showQuiz();
else{var found=sections.filter(function(s){return s.id===id;})[0];if(found)lesson(found);else home();}
window.scrollTo(0,0);main.focus({preventScroll:true});
}
document.getElementById('print').onclick=function(){window.print();};
document.getElementById('reset').onclick=function(){if(confirm('Azzero progresso e verifica di Boccaccio su questo dispositivo?')){localStorage.removeItem(KEY);state={read:[],quiz:null};nav();}};
window.addEventListener('hashchange',nav);
nav();
if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').then(function(){document.getElementById('offline').textContent='· contenuti principali disponibili offline';}).catch(function(){});}