'use strict';
var KEY='gbprof-rinascimento-v1';
var state={read:[],quiz:null};
try{var saved=JSON.parse(localStorage.getItem(KEY)||'{}');state.read=saved.read||[];state.quiz=saved.quiz||null;}catch(e){}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
var main=document.getElementById('main');

var sections=[
{id:'continuita',title:'Continuità e sviluppo',sub:'Dal metodo umanistico alle forme del Cinquecento',body:"<p class='kicker'>Tappa 1</p><h1>Continuità e sviluppo</h1><p>La lezione di partenza coglie bene un punto: Umanesimo e Rinascimento non sono due mondi separati. Il Cinquecento sviluppa molte conquiste del Quattrocento: studio dei classici, fiducia nelle capacità umane, cultura delle corti, filologia e attenzione alla forma.</p><h3>Che cosa cambia?</h3><p>Nel Rinascimento il patrimonio umanistico diventa sempre più <strong>forma condivisa</strong>: lingua, stile, modelli letterari, comportamento di corte, arti figurative, pensiero politico. L’antico non è soltanto studiato; diventa un criterio con cui costruire il presente.</p><div class='split'><div class='pole form'><strong>Umanesimo</strong><p>ritorno alle fonti, filologia, educazione, riscoperta dei classici.</p></div><div class='pole crisis'><strong>Rinascimento</strong><p>uso creativo e normativo dei modelli antichi nella lingua, nelle arti e nella vita politica.</p></div></div><div class='quote'>Il Rinascimento non “sostituisce” l’Umanesimo: lo porta dentro le forme della vita culturale.</div>"},
{id:'italia',title:'Splendore e fragilità',sub:'Una civiltà raffinatissima dentro una crisi politica',body:"<p class='kicker'>Tappa 2</p><h1>Splendore e fragilità</h1><p>La vecchia lezione usa il 1492 come data simbolica per il passaggio al nuovo secolo. È utile, ma per capire l’Italia rinascimentale conviene affiancarle altre date che mostrano la crisi politica.</p><div class='timeline'><div class='time-row'><strong>1492</strong><span>nuove rotte atlantiche cambiano progressivamente gli equilibri economici europei.</span></div><div class='time-row'><strong>1494</strong><span>la discesa di Carlo VIII apre la lunga stagione delle guerre d’Italia.</span></div><div class='time-row'><strong>1527</strong><span>il Sacco di Roma diventa il simbolo traumatico della vulnerabilità italiana.</span></div><div class='time-row'><strong>1559</strong><span>la pace di Cateau-Cambrésis sancisce il predominio spagnolo su larga parte della penisola.</span></div></div><h3>Il paradosso</h3><p>Mentre l’Italia perde autonomia politica, le sue corti producono modelli artistici e letterari che diventano europei.</p><div class='quote'>La forma si perfeziona proprio mentre il sistema politico che la sostiene si indebolisce.</div>"},
{id:'classicismo',title:'Classicismo e regola',sub:'Imitare non significa copiare',body:"<p class='kicker'>Tappa 3</p><h1>Classicismo e regola</h1><p>Il Rinascimento porta a maturazione il bisogno di modelli. Ma l’imitazione non è semplice riproduzione: significa selezionare, combinare e trasformare esempi riconosciuti come eccellenti.</p><h3>Lingua</h3><p>Con Pietro Bembo il volgare letterario riceve un modello forte: Petrarca per la poesia, Boccaccio per la prosa. La questione della lingua diventa una questione di norma e prestigio.</p><h3>Generi</h3><p>La riflessione sulle forme letterarie cresce lungo tutto il secolo. La <em>Poetica</em> di Aristotele diventerà soprattutto nel secondo Cinquecento un punto centrale delle discussioni sulle regole dei generi.</p><div class='split'><div class='pole form'><strong>Misura</strong><p>ordine, proporzione, controllo formale, equilibrio.</p></div><div class='pole crisis'><strong>Invenzione</strong><p>il modello antico viene adattato a una realtà nuova e spesso instabile.</p></div></div>"},
{id:'corte',title:'La corte come scena',sub:'Prestigio, comportamento e dipendenza',body:"<p class='kicker'>Tappa 4</p><h1>La corte come scena</h1><p>La corte rinascimentale è insieme luogo di produzione culturale e sistema di potere. Qui letterati, artisti e diplomatici trovano protezione, pubblico e prestigio; ma anche dipendenza.</p><h3>L’ideale del cortigiano</h3><p>Il Rinascimento elabora un modello di comportamento fondato su misura, controllo, eleganza, competenza e capacità di nascondere lo sforzo. È il mondo della <em>sprezzatura</em>: l’arte di far apparire naturale ciò che è costruito con disciplina.</p><h3>Ariosto</h3><p>Nell’<em>Orlando furioso</em> equilibrio formale e libertà fantastica convivono. Ma dietro la leggerezza dell’intreccio resta una lucida consapevolezza delle passioni, delle illusioni e dei limiti umani.</p><div class='quote'>La corte produce armonia come stile; non elimina il conflitto della realtà.</div>"},
{id:'machiavelli',title:'Machiavelli: guardare ciò che accade',sub:'Verità effettuale, virtù e fortuna',body:"<p class='kicker'>Tappa 5</p><h1>Machiavelli</h1><p>La tua lezione individua giustamente la svolta: Machiavelli osserva la politica a partire dagli effetti concreti delle azioni, non da un modello ideale di principe perfetto.</p><h3>La verità effettuale</h3><p>Il punto non è proclamare che “la morale non conta”, ma distinguere il problema politico da quello morale: governare significa confrontarsi con conflitto, necessità, consenso, forza e imprevedibilità.</p><h3>Virtù e fortuna</h3><p>La fortuna indica ciò che sfugge al controllo; la virtù è la capacità politica di leggere l’occasione, adattarsi e agire con efficacia.</p><h3>Volpe e leone</h3><p>Il principe deve saper riconoscere che forza e astuzia rispondono a situazioni differenti. Non è una celebrazione astratta della violenza, ma un’analisi della lotta politica.</p><div class='quote'>Machiavelli non costruisce un principe “ideale”: costruisce uno strumento per pensare la politica reale.</div>"},
{id:'mandragola',title:'La Mandragola',sub:'La stessa logica del potere dentro una commedia',body:"<p class='kicker'>Tappa 6</p><h1>La Mandragola</h1><p>La vecchia lezione racconta bene il meccanismo del raggiro: Callimaco desidera Lucrezia, Ligurio orchestra l’inganno, Nicia viene manipolato, fra Timoteo mette la propria autorità religiosa al servizio dell’interesse.</p><h3>Perché è più di una commedia?</h3><p>Ogni personaggio agisce seguendo un interesse preciso. Il sistema funziona perché qualcuno comprende i desideri degli altri e li usa come leve.</p><div class='timeline'><div class='time-row'><strong>Callimaco</strong><span>desiderio amoroso</span></div><div class='time-row'><strong>Ligurio</strong><span>intelligenza strategica</span></div><div class='time-row'><strong>Nicia</strong><span>vanità e ossessione per l’erede</span></div><div class='time-row'><strong>Timoteo</strong><span>interesse economico e opportunismo</span></div><div class='time-row'><strong>Lucrezia</strong><span>da oggetto del piano a soggetto capace di governarne l’esito</span></div></div><div class='quote'>La commedia mostra in piccolo ciò che il Principe osserva in grande: gli uomini si muovono attraverso interessi, paure e occasioni.</div>"},
{id:'guicciardini',title:'Guicciardini: nessuna regola basta',sub:'Discrezione, particolare e irripetibilità dei casi',body:"<p class='kicker'>Tappa 7</p><h1>Guicciardini</h1><p>La tua lezione lo presenta come più concreto e meno fiducioso nei modelli generali. È una buona intuizione, purché non lo riduciamo a semplice rassegnazione.</p><h3>Discrezione</h3><p>È la capacità di distinguere caso per caso. La storia non offre formule automatiche: circostanze simili possono produrre risultati diversi perché cambiano persone, condizioni e rapporti di forza.</p><h3>Il particolare</h3><p>Non significa banalmente egoismo. Indica anche l’attenzione agli interessi concreti che muovono individui e gruppi.</p><div class='quote'>Se Machiavelli cerca regolarità dentro il conflitto, Guicciardini diffida delle regole troppo generali.</div>"},
{id:'crisi',title:'Dal Rinascimento alla Controriforma',sub:'Quando l’equilibrio si incrina',body:"<p class='kicker'>Tappa 8</p><h1>Dal Rinascimento alla Controriforma</h1><p>La seconda metà del Cinquecento cambia il clima culturale. La tua lezione richiama due passaggi essenziali: la pace di Cateau-Cambrésis del 1559 e il Concilio di Trento, concluso nel 1563.</p><h3>Controllo e disciplina</h3><p>La Chiesa cattolica rafforza strumenti educativi, pastorali e anche censori. Il problema della conformità religiosa entra più profondamente nella produzione culturale.</p><h3>Tasso</h3><p>La sua opera rende visibile questa nuova tensione: desiderio e norma, eroismo e colpa, piacere poetico e disciplina morale.</p><div class='split'><div class='pole form'><strong>Primo Cinquecento</strong><p>fiducia nella forma, nella misura e nella capacità di governare l’esperienza.</p></div><div class='pole crisis'><strong>Secondo Cinquecento</strong><p>crescono inquietudine, controllo, conflitto religioso e crisi delle certezze.</p></div></div><div class='quote'>Il Rinascimento non finisce all’improvviso: la sua armonia si trasforma in tensione.</div>"}
];

function mapCore(){return "<div class='map'><div class='map-lines'></div><div class='node n1'><strong>Forma</strong>misura, classicismo, lingua</div><div class='node n2'><strong>Potere</strong>corti, diplomazia, guerra</div><div class='node n3'><strong>Realtà</strong>verità effettuale, interessi, conflitto</div><div class='node n4'><strong>Crisi</strong>guerre d’Italia, 1527, 1559, Trento</div><div class='map-center'>RINASCIMENTO<br><small>ordine dentro l’instabilità</small></div></div>";}

function sourceNote(){return "<section class='panel sources'><h3>Materiale di partenza</h3><p>La PWA rielabora la lezione di gbprof <em>Il Rinascimento</em>: continuità con l’Umanesimo, classicismo, Ariosto, Bembo, Machiavelli, <em>Mandragola</em>, Guicciardini e secondo Cinquecento. Ho conservato questi nuclei, ma ho distinto alcune formulazioni troppo schematiche: Machiavelli non è presentato come teorico di un principe “ideale” né come semplice separazione della politica da ogni morale; Guicciardini non è ridotto a cinico rassegnato; la codificazione aristotelica è collocata soprattutto nel secondo Cinquecento.</p></section>";}

function home(){
var pct=Math.round(state.read.length/sections.length*100);
var cards=sections.map(function(s,i){return "<a class='lesson' href='#"+s.id+"'><span class='n'>0"+(i+1)+"</span><h3>"+s.title+"</h3><p>"+s.sub+"</p></a>";}).join('');
main.innerHTML="<section class='hero'><div class='hero-copy'><span class='chip'>Letteratura · III anno</span><p class='eyebrow'>Cinquecento</p><h1>La forma e la crisi</h1><p class='lead'>Il Rinascimento costruisce equilibrio, misura e modelli perfetti mentre l’Italia attraversa guerre, invasioni e perdita di autonomia.</p><div class='cta'><a class='button' href='#continuita'>Inizia il percorso</a><a class='button secondary' href='#mappe'>Apri le mappe</a></div></div><div class='hero-visual'><img src='copertina.svg' alt='Copertina del Rinascimento: geometria, prospettiva e città rinascimentale attraversate da una frattura che rappresenta la crisi politica del Cinquecento'></div></section><div class='wrap'><section class='intro'><div class='panel'><p class='kicker'>La tesi</p><h2>L’armonia rinascimentale non cancella la crisi: la contiene.</h2><p>La forma diventa un modo per governare un mondo che appare sempre più complesso e instabile.</p></div><div class='panel'><p class='kicker'>Il tuo percorso</p><h2>"+state.read.length+"/"+sections.length+" tappe completate</h2><div class='progress'><span style='width:"+pct+"%'></span></div><p class='muted'>Il progresso resta salvato su questo dispositivo.</p></div></section><section class='section'><div class='section-head'><p class='kicker'>Percorso</p><h2>Otto tappe dall’equilibrio alla frattura</h2></div><div class='route'>"+cards+"</div></section><section class='section'><div class='section-head'><p class='kicker'>Mappa generale</p><h2>Quattro forze definiscono il secolo</h2></div>"+mapCore()+"</section>"+sourceNote()+"</div>";
}

function lesson(s){
main.innerHTML="<div class='wrap'><div class='content-grid'><article class='article'>"+s.body+"<div class='cta'><a class='button' href='#home'>← Indice</a><a class='button' href='#mappe'>Mappe</a></div></article><aside class='aside'><div class='panel'><p class='kicker'>Tappa</p><h3>"+s.title+"</h3><p>"+s.sub+"</p><button id='mark'>"+(state.read.indexOf(s.id)>=0?"✓ Completata":"Segna come completata")+"</button></div><div class='panel'><strong>Domanda chiave</strong><p>Dove si vede qui il contrasto fra forma e instabilità?</p></div></aside></div></div>";
document.getElementById('mark').onclick=function(){var i=state.read.indexOf(s.id);if(i>=0)state.read.splice(i,1);else state.read.push(s.id);save();lesson(s);};
}

function showMaps(){
main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Mappe concettuali</p><h2>Il Rinascimento come equilibrio instabile</h2></section>"+mapCore()+"<section class='section'><div class='concept'><div class='panel'><span class='big'>Forma</span><h3>classicismo</h3><p>modelli, misura, lingua, generi</p></div><div class='panel'><span class='big'>Azione</span><h3>Machiavelli</h3><p>virtù, occasione, realtà effettuale</p></div><div class='panel'><span class='big'>Caso</span><h3>Guicciardini</h3><p>discrezione, circostanze, particolare</p></div></div></section><section class='section'><div class='panel'><h2>Cronologia della frattura</h2><div class='timeline'><div class='time-row'><strong>1492</strong><span>nuovo asse atlantico dei commerci</span></div><div class='time-row'><strong>1494</strong><span>iniziano le guerre d’Italia</span></div><div class='time-row'><strong>1527</strong><span>Sacco di Roma</span></div><div class='time-row'><strong>1559</strong><span>Cateau-Cambrésis e predominio spagnolo</span></div><div class='time-row'><strong>1563</strong><span>conclusione del Concilio di Trento</span></div></div></div></section><section class='section'><div class='panel'><h2>Dall’Umanesimo al Rinascimento</h2><div class='split'><div class='pole form'><strong>Prima</strong><p>recuperare, leggere, comprendere i modelli antichi.</p></div><div class='pole crisis'><strong>Poi</strong><p>usarli per costruire lingua, arte, comportamento e pensiero politico.</p></div></div></div></section></div>";
}

function showCompare(){
main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Confronto</p><h2>Machiavelli e Guicciardini</h2><p>Non due opposti assoluti, ma due diversi modi di pensare la relazione fra esperienza, storia e decisione.</p></section><div class='comparison'><section class='compare-col'><span class='badge'>Machiavelli</span><h3>Cercare regolarità</h3><ul><li>La storia offre esempi e ricorrenze.</li><li>La politica richiede capacità di leggere conflitti e rapporti di forza.</li><li>La virtù prova a governare almeno in parte la fortuna.</li><li>L’azione politica può richiedere scelte dure o non convenzionali.</li><li>Il problema è come fondare e conservare un ordine politico.</li></ul></section><section class='compare-col'><span class='badge'>Guicciardini</span><h3>Distinguere i casi</h3><ul><li>Le analogie storiche non producono ricette automatiche.</li><li>Ogni situazione dipende da circostanze specifiche.</li><li>La discrezione vale più di una regola universale.</li><li>Gli interessi concreti sono decisivi nell’azione umana.</li><li>Il politico efficace deve valutare il particolare.</li></ul></section></div><section class='section'><div class='panel'><h2>Il punto comune</h2><p>Entrambi guardano alla politica senza rifugiarsi in un modello astratto. Il loro dissenso riguarda soprattutto <strong>quanto sia possibile generalizzare dall’esperienza storica</strong>.</p></div></section></div>";
}

var questions=[
["Qual è la tesi centrale della PWA?",["Il Rinascimento è un’età senza crisi","La forma rinascimentale convive con una profonda instabilità politica","Il Rinascimento coincide con l’Umanesimo"],1],
["Che rapporto c’è fra Umanesimo e Rinascimento?",["Rottura totale","Continuità e sviluppo","Nessun rapporto"],1],
["Quale data apre simbolicamente le guerre d’Italia?",["1494","1453","1563"],0],
["Che cosa fa Bembo?",["Propone modelli letterari forti per il volgare","Rifiuta il volgare","Scrive il Principe"],0],
["Che cosa significa verità effettuale in Machiavelli?",["Descrivere come gli uomini dovrebbero essere","Osservare come funzionano davvero azioni e rapporti politici","Negare ogni forma di morale personale"],1],
["Che cos’è la virtù machiavelliana?",["Bontà religiosa","Capacità politica di leggere occasione e agire","Fortuna favorevole"],1],
["Perché la Mandragola è collegata al Principe?",["Perché è un trattato politico","Perché mostra interessi, strategie e manipolazione in forma comica","Perché parla di guerra"],1],
["Che cos’è la discrezione in Guicciardini?",["Obbedienza al principe","Capacità di valutare caso per caso","Segretezza diplomatica"],1],
["Che cosa indica il 1559?",["La scoperta dell’America","La pace di Cateau-Cambrésis","La morte di Machiavelli"],1],
["Quale autore rappresenta la tensione del secondo Cinquecento nella PWA?",["Tasso","Dante","Petrarca"],0]
];

function showQuiz(){
var html=questions.map(function(q,i){var opts=q[1].map(function(o,j){return "<label class='option'><input type='radio' name='q"+i+"' value='"+j+"' required> "+o+"</label>";}).join('');return "<fieldset><legend>"+(i+1)+". "+q[0]+"</legend>"+opts+"</fieldset>";}).join('');
main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Verifica</p><h2>Hai capito il Rinascimento oltre gli stereotipi?</h2></section><form id='quiz' class='panel quiz'>"+html+"<button>Correggi</button></form><div id='out'></div></div>";
document.getElementById('quiz').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),c=0;questions.forEach(function(q,i){if(Number(f.get('q'+i))===q[2])c++;});state.quiz={score:c,date:new Date().toISOString()};save();var msg=c===10?"Hai colto tutti i nessi principali.":c>=7?"La struttura è compresa; ripassa i passaggi meno sicuri.":"Torna alle mappe: distingui prima forma, potere, realtà e crisi.";document.getElementById('out').innerHTML="<div class='result'><h3>"+c+"/10</h3><p>"+msg+"</p></div>";};
}

function nav(){
var id=location.hash.slice(1)||'home';
if(id==='home')home();
else if(id==='mappe')showMaps();
else if(id==='confronto')showCompare();
else if(id==='verifica')showQuiz();
else{var found=sections.filter(function(s){return s.id===id;})[0];if(found)lesson(found);else home();}
window.scrollTo(0,0);main.focus({preventScroll:true});
}
document.getElementById('print').onclick=function(){window.print();};
document.getElementById('reset').onclick=function(){if(confirm('Azzero progresso e verifica del Rinascimento su questo dispositivo?')){localStorage.removeItem(KEY);state={read:[],quiz:null};nav();}};
window.addEventListener('hashchange',nav);nav();
if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').then(function(){document.getElementById('offline').textContent='· disponibile offline';}).catch(function(){});}