'use strict';
var KEY='gbprof-petrarca-v1';
var state={read:[],quiz:null};
try{var saved=JSON.parse(localStorage.getItem(KEY)||'{}');state.read=saved.read||[];state.quiz=saved.quiz||null;}catch(e){}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
var main=document.getElementById('main');
var sections=[
{id:'dante-petrarca',title:'Dante e Petrarca',sub:'Dalla coerenza del cosmo alla coscienza divisa',body:"<p class='kicker'>Tappa 1</p><h1>Dante e Petrarca</h1><p class='muted'>Due modi diversi di stare nel mondo, non due caricature.</p><h3>Dante: un universo ordinabile</h3><p>Dante può rappresentare una realtà vastissima perché la pensa entro un ordine morale, politico e religioso. La pluralità delle voci confluisce in una costruzione complessiva: il viaggio della <em>Commedia</em> tende a dare senso al mondo.</p><h3>Petrarca: il conflitto entra nell’io</h3><p>Con Petrarca il centro si restringe e, proprio per questo, diventa più profondo. Non è l’intero cosmo a chiedere spiegazione: è Francesco stesso. Amore, gloria, fede, memoria e desiderio non si lasciano ricomporre una volta per tutte.</p><div class='split'><div class='pole good'><strong>Dante</strong><p>Molte voci, una visione ordinatrice. L’intellettuale interviene nel mondo.</p></div><div class='pole desire'><strong>Petrarca</strong><p>Una voce, molte tensioni. L’intellettuale osserva e riscrive se stesso.</p></div></div><div class='quote'>La vera novità non è «Petrarca moderno» in senso assoluto: è l’intensità con cui l’io diventa problema.</div>"},
{id:'tempo',title:'Fra Medioevo e Umanesimo',sub:'Classici, otium, filologia e inquietudine',body:"<p class='kicker'>Tappa 2</p><h1>Fra Medioevo e Umanesimo</h1><p>Petrarca ama i classici non come semplici autorità da piegare al presente, ma come interlocutori storicamente lontani. Ricerca codici, confronta testi, scrive lettere ideali agli antichi: il passato diventa una civiltà da comprendere.</p><h3>L’otium</h3><p>Lo studio è uno spazio sottratto al rumore del mondo. Ma non è fuga pura: nella solitudine Petrarca incontra proprio ciò da cui non può fuggire, cioè se stesso.</p><h3>Una soglia culturale</h3><p>Petrarca resta cristiano e sente il richiamo della salvezza, ma attribuisce alla cultura classica un valore autonomo straordinario. È questa tensione, più che una rottura netta, a renderlo decisivo nella nascita dell’Umanesimo.</p><div class='timeline'><div class='time-row'><strong>Antichi</strong><span>modelli di lingua, stile, virtù e dialogo interiore</span></div><div class='time-row'><strong>Presente</strong><span>percepito spesso come età impoverita e dispersiva</span></div><div class='time-row'><strong>Io</strong><span>il luogo in cui antico e cristiano entrano in tensione</span></div></div>"},
{id:'secretum',title:'Il Secretum',sub:'Francesco contro Francesco',body:"<p class='kicker'>Tappa 3</p><h1>Il Secretum</h1><p>Nel <em>Secretum</em> Petrarca mette in scena un dialogo fra Francesco e sant’Agostino, alla presenza allegorica della Verità. Non è una disputa scolastica: è un dramma della coscienza.</p><div class='split'><div class='pole desire'><strong>Francesco</strong><p>Difende il valore dell’amore, della gloria, della bellezza e della propria esperienza.</p></div><div class='pole good'><strong>Agostino</strong><p>Smonta le giustificazioni di Francesco e gli mostra quanto desiderio e vanità lo trattengano.</p></div></div><h3>Perché è importante?</h3><p>Perché la soluzione non cancella il conflitto. Petrarca sa ciò che dovrebbe volere, ma non coincide con ciò che desidera. Questa distanza fra conoscenza e volontà è il cuore del suo autoritratto.</p><div class='quote'>Non un uomo senza valori, ma un uomo che non riesce a diventare uno.</div>"},
{id:'canzoniere',title:'Il Canzoniere',sub:'Dare forma ai frammenti',body:"<p class='kicker'>Tappa 4</p><h1>Il Canzoniere</h1><p>Il titolo latino <em>Rerum vulgarium fragmenta</em> indica «frammenti di cose in volgare». Le liriche nascono in tempi diversi e vengono continuamente selezionate, corrette e ordinate.</p><h3>366 componimenti</h3><p>Il libro comprende 366 testi. La tradizionale distinzione fra rime «in vita» e «in morte» di Laura è utile, ma non va pensata come una cesura biografica perfettamente meccanica: l’ordine del libro è prima di tutto una costruzione poetica.</p><h3>Un libro che guarda all’indietro</h3><p>Il primo sonetto presenta l’amore come «giovenile errore». Chi parla è un io successivo che giudica l’io di allora. Per questo il <em>Canzoniere</em> non è un diario immediato: è memoria organizzata, riscrittura, montaggio.</p><div class='quote'>Il titolo dice «frammenti»; il libro prova a trasformarli in una forma.</div>"},
{id:'laura',title:'Laura',sub:'Donna, nome, memoria, simbolo',body:"<p class='kicker'>Tappa 5</p><h1>Laura</h1><p>La Laura storica rimane incerta: l’identificazione tradizionale con Laura de Noves non può essere trattata come un fatto documentato. La Laura poetica, invece, è chiarissima nella sua funzione: è il punto in cui desiderio, memoria, tempo e poesia si incontrano.</p><h3>Non Beatrice 2.0</h3><p>Laura conserva elementi della tradizione cortese e stilnovistica, ma non svolge la stessa funzione teologica di Beatrice. La sua presenza resta legata alla vicenda interiore del poeta.</p><h3>Una figura costruita dalla memoria</h3><p>Capelli, occhi, passo, sorriso: i tratti sono spesso convenzionali. Ciò che cambia davvero è il tempo. Laura è ricordata, perduta, immaginata, vista attraverso il prima e l’ora.</p><div class='split'><div class='pole desire'><strong>Desiderio</strong><p>Laura come presenza che attrae e rende inquieto.</p></div><div class='pole good'><strong>Memoria</strong><p>Laura come immagine che il tempo trasforma e rende poetica.</p></div></div>"},
{id:'memoria',title:'Memoria e paesaggio',sub:'La realtà diventa interiore',body:"<p class='kicker'>Tappa 6</p><h1>Memoria e paesaggio</h1><p>In Petrarca il paesaggio non è semplice sfondo. Natura e tempo vengono filtrati dalla coscienza. In <em>Chiare, fresche et dolci acque</em> il luogo è contemporaneamente reale, ricordato e immaginato.</p><h3>Passato, presente, futuro</h3><p>Il testo ondeggia fra l’apparizione passata di Laura, il dolore presente e una fantasia futura di morte e pietà. Il paesaggio diventa la forma sensibile di questo movimento mentale.</p><h3>«Erano i capei d’oro…»</h3><p>Anche qui la distanza decisiva è fra «erano» e «or». La bellezza non viene presentata in un eterno presente: viene recuperata da un io che sa che il tempo è passato.</p><div class='quote'>La realtà che conta non è soltanto ciò che fu, ma ciò che la memoria ne fa.</div>"},
{id:'solo',title:'Solo et pensoso',sub:'Il vero protagonista è Francesco',body:"<p class='kicker'>Tappa 7</p><h1>Solo et pensoso</h1><p>Nel sonetto più emblematico della solitudine petrarchesca, il poeta percorre luoghi deserti per sottrarsi allo sguardo altrui. Ma non può sottrarsi ad Amore.</p><h3>Spazio esterno e spazio interno</h3><p>Il cammino lento, i campi deserti, lo sguardo abbassato sono un autoritratto psicologico. Petrarca prova a costruire distanza dal mondo, ma porta con sé la propria passione.</p><h3>La conclusione del percorso</h3><p>Laura domina molte liriche, ma il protagonista del libro è Francesco: colui che desidera, ricorda, si giudica, si contraddice e infine trasforma questa instabilità in stile.</p><div class='quote'>Dante attraversa l’aldilà per comprendere il mondo. Petrarca attraversa se stesso senza arrivare a possederlo interamente.</div>"}
];
var texts=[
{t:"Voi ch’ascoltate in rime sparse il suono",tag:"proemio",d:"Il presente giudica il passato: errore, vergogna, pentimento, brevità delle cose mondane."},
{t:"Solo et pensoso i più deserti campi",tag:"io e spazio",d:"La solitudine fisica non elimina il conflitto interiore: Amore cammina con il poeta."},
{t:"Chiare, fresche et dolci acque",tag:"memoria",d:"Paesaggio, ricordo e fantasia si sovrappongono; il luogo diventa paesaggio mentale."},
{t:"Erano i capei d’oro a l’aura sparsi",tag:"tempo",d:"Il contrasto fra passato e presente trasforma l’apparizione amorosa in memoria."}
];
function mapCore(){return "<div class='map'><div class='map-lines'></div><div class='node n1'><strong>Laura</strong>desiderio, assenza, memoria</div><div class='node n2'><strong>Gloria</strong>poesia, fama, classici</div><div class='node n3'><strong>Dio</strong>salvezza, pentimento, misura</div><div class='node n4'><strong>Tempo</strong>perdita, mutamento, riscrittura</div><div class='map-center'>Francesco<br><small>io diviso</small></div></div>";}
function home(){
var pct=Math.round(state.read.length/sections.length*100);
var cards=sections.map(function(s,i){return "<a class='lesson' href='#"+s.id+"'><span class='n'>0"+(i+1)+"</span><h3>"+s.title+"</h3><p>"+s.sub+"</p></a>";}).join('');
main.innerHTML="<section class='hero'><div class='hero-copy'><span class='chip'>Letteratura · III anno</span><p class='eyebrow'>Francesco Petrarca</p><h1>L’io<br>diviso</h1><p class='lead'>Amore, memoria, gloria e tempo. Non una biografia da imparare, ma un conflitto da attraversare.</p><div class='cta'><a class='button' href='#dante-petrarca'>Inizia il percorso</a><a class='button secondary' href='#mappe'>Apri le mappe</a></div></div><div class='hero-visual' aria-label='Copertina grafica astratta dedicata a Petrarca'><div class='axis'></div><div class='portrait'></div></div></section><div class='wrap'><section class='intro'><div class='panel'><p class='kicker'>La tesi</p><h2>Il centro non è Laura. È Francesco.</h2><p>Laura è decisiva, ma il vero oggetto della poesia è l’io che la desidera, la ricorda e la trasforma in parola.</p></div><div class='panel'><p class='kicker'>Il tuo percorso</p><h2>"+state.read.length+"/"+sections.length+" tappe completate</h2><div class='progress'><span style='width:"+pct+"%'></span></div><p class='muted'>Il progresso resta salvato su questo dispositivo.</p></div></section><section class='section'><div class='section-head'><p class='kicker'>Percorso</p><h2>Sette tappe per entrare nella coscienza petrarchesca</h2></div><div class='route'>"+cards+"</div></section><section class='section'><div class='section-head'><p class='kicker'>Idea-guida</p><h2>Quattro forze tirano lo stesso io</h2></div>"+mapCore()+"</section></div>";
}
function lesson(s){
main.innerHTML="<div class='wrap'><div class='content-grid'><article class='article'>"+s.body+"<div class='cta'><a class='button' href='#home'>← Indice</a><a class='button' href='#mappe'>Mappe</a></div></article><aside class='aside'><div class='panel'><p class='kicker'>Mappa del percorso</p><h3>"+s.title+"</h3><p>"+s.sub+"</p><button id='mark'>"+(state.read.indexOf(s.id)>=0?"✓ Completata":"Segna come completata")+"</button></div><div class='panel'><strong>Domanda chiave</strong><p>Che cosa cambia quando la realtà viene filtrata dalla memoria dell’io?</p></div></aside></div></div>";
document.getElementById('mark').onclick=function(){var i=state.read.indexOf(s.id);if(i>=0)state.read.splice(i,1);else state.read.push(s.id);save();lesson(s);};
}
function showTexts(){
var cards=texts.map(function(x){return "<article class='text-card'><span class='tag'>"+x.tag+"</span><h3>"+x.t+"</h3><p>"+x.d+"</p></article>";}).join('');
main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Testi</p><h2>Quattro testi, quattro porte</h2><p>Non sono «brani da fare»: ognuno verifica una parte dell’ipotesi sull’io petrarchesco.</p></section><div class='texts'>"+cards+"</div><section class='section'><div class='panel'><h2>Schema di lettura</h2><div class='concept'><div class='panel'><span class='big'>1</span><h3>Tempo</h3><p>Quale rapporto c’è fra prima e ora?</p></div><div class='panel'><span class='big'>2</span><h3>Io</h3><p>Chi parla e da quale posizione?</p></div><div class='panel'><span class='big'>3</span><h3>Forma</h3><p>Come ritmo e immagini rendono visibile il conflitto?</p></div></div></div></section></div>";
}
function showMaps(){
main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Mappe concettuali</p><h2>Vedere i nessi, non decorare la lezione</h2></section>"+mapCore()+"<section class='section'><div class='concept'><div class='panel'><span class='big'>Dante</span><h3>ordine</h3><p>pluralità del reale → costruzione unitaria → senso</p></div><div class='panel'><span class='big'>Petrarca</span><h3>frammento</h3><p>esperienza → memoria → giudizio → nuova riscrittura</p></div><div class='panel'><span class='big'>Laura</span><h3>tempo</h3><p>presenza → assenza → ricordo → figura poetica</p></div></div></section><section class='section'><div class='panel'><h2>La mappa del Canzoniere</h2><div class='timeline'><div class='time-row'><strong>Evento</strong><span>esperienza amorosa e biografica</span></div><div class='time-row'><strong>Memoria</strong><span>il passato viene recuperato da un io diverso</span></div><div class='time-row'><strong>Giudizio</strong><span>errore, vergogna, pentimento e nostalgia convivono</span></div><div class='time-row'><strong>Forma</strong><span>i frammenti vengono selezionati e ordinati in un libro</span></div></div></div></section></div>";
}
var questions=[
["Nel percorso proposto, qual è il vero centro del Canzoniere?",["Laura come personaggio storico","Francesco e il suo conflitto interiore","La politica comunale"],1],
["Perché il Canzoniere non è semplicemente un diario?",["Perché è scritto tutto in latino","Perché elimina ogni dato biografico","Perché organizza e riscrive retrospettivamente esperienze e testi"],2],
["Nel Secretum, Agostino rappresenta soprattutto…",["La voce critica che interroga le auto-giustificazioni di Francesco","Un antagonista politico","Un biografo di Laura"],0],
["Che funzione assume spesso il paesaggio?",["Solo decorativa","Specchio e costruzione della coscienza","Documentazione geografica"],1],
["Quale formula descrive meglio il rapporto Dante/Petrarca usato nella PWA?",["Dante senza conflitti / Petrarca senza fede","Ordine del mondo / conflitto dell’io","Politica / assenza totale di politica"],1]
];
function showQuiz(){
var html=questions.map(function(q,i){var opts=q[1].map(function(o,j){return "<label class='option'><input type='radio' name='q"+i+"' value='"+j+"' required> "+o+"</label>";}).join('');return "<fieldset><legend>"+(i+1)+". "+q[0]+"</legend>"+opts+"</fieldset>";}).join('');
main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Verifica</p><h2>Controlla se hai afferrato i nessi</h2></section><form id='quiz' class='panel quiz'>"+html+"<button>Correggi</button></form><div id='out'></div></div>";
document.getElementById('quiz').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),c=0;questions.forEach(function(q,i){if(Number(f.get('q'+i))===q[2])c++;});state.quiz={score:c,date:new Date().toISOString()};save();document.getElementById('out').innerHTML="<div class='result'><h3>"+c+"/5</h3><p>"+(c===5?"Hai colto tutti i nessi principali.":c>=3?"La struttura è compresa; ripassa le tappe meno sicure.":"Rientra nelle mappe: prima dei dettagli servono i rapporti fra i concetti.")+"</p></div>";};
}
function nav(){
var id=location.hash.slice(1)||'home';
if(id==='home')home();else if(id==='testi')showTexts();else if(id==='mappe')showMaps();else if(id==='verifica')showQuiz();else{var found=sections.filter(function(s){return s.id===id;})[0];if(found)lesson(found);else home();}
window.scrollTo(0,0);main.focus({preventScroll:true});
}
document.getElementById('print').onclick=function(){window.print();};
document.getElementById('reset').onclick=function(){if(confirm('Azzero progresso e verifica di Petrarca su questo dispositivo?')){localStorage.removeItem(KEY);state={read:[],quiz:null};nav();}};
window.addEventListener('hashchange',nav);nav();
if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').then(function(){document.getElementById('offline').textContent='· disponibile offline';}).catch(function(){});}