'use strict';
var KEY='gbprof-umanesimo-v1';
var state={read:[],quiz:null};
try{var saved=JSON.parse(localStorage.getItem(KEY)||'{}');state.read=saved.read||[];state.quiz=saved.quiz||null;}catch(e){}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
var main=document.getElementById('main');

var sections=[
{id:'soglia',title:'Una soglia, non un muro',sub:'Perché Medioevo e Umanesimo non si separano con una data',body:"<p class='kicker'>Tappa 1</p><h1>Una soglia, non un muro</h1><p class='muted'>La tua vecchia lezione parte da un’idea giusta: dividere la storia in epoche è utile, ma è sempre una forzatura.</p><h3>Che cosa cambia davvero?</h3><p>Fra Trecento e Quattrocento alcuni studiosi sviluppano una coscienza più forte della distanza che li separa dall’antichità. I classici non sono più soltanto autorità da usare: diventano testi appartenenti a un altro tempo, da ricostruire, confrontare, comprendere.</p><div class='split'><div class='pole old'><strong>Continuità</strong><p>fede cristiana, università, cultura latina, corti e città non scompaiono.</p></div><div class='pole new'><strong>Novità</strong><p>crescono il senso storico, la filologia, il valore educativo dei classici e una nuova fiducia nelle capacità umane.</p></div></div><div class='quote'>L’Umanesimo non comincia quando “finisce” il Medioevo. Nasce dentro il Medioevo, modificando il modo di guardare il passato e l’uomo.</div>"},
{id:'fonti',title:'Ad fontes: la rivoluzione filologica',sub:'Il passato diventa un problema da verificare',body:"<p class='kicker'>Tappa 2</p><h1>Ad fontes</h1><p>Il cuore dell’Umanesimo non è uno slogan sull’uomo: è prima di tutto un <strong>metodo</strong>. Cercare manoscritti, confrontare varianti, riconoscere interpolazioni, ricostruire parole e contesti.</p><h3>Perché è rivoluzionario?</h3><p>Perché un testo antico non viene più accettato soltanto perché autorevole. L’umanista chiede: quale manoscritto è più attendibile? Questa parola era davvero nell’originale? Quando è stato scritto? Che cosa significava allora?</p><div class='timeline'><div class='time-row'><strong>Ricercare</strong><span>ritrovare codici dimenticati nelle biblioteche</span></div><div class='time-row'><strong>Confrontare</strong><span>mettere a confronto copie diverse dello stesso testo</span></div><div class='time-row'><strong>Correggere</strong><span>ricostruire una forma più attendibile</span></div><div class='time-row'><strong>Contestualizzare</strong><span>capire il testo nel suo tempo, non piegarlo automaticamente al presente</span></div></div><p>È qui che Petrarca diventa un precursore decisivo e che, nel Quattrocento, figure come Lorenzo Valla porteranno la critica linguistica a risultati clamorosi.</p>"},
{id:'humanitas',title:'Humanitas: formare l’uomo',sub:'Studia humanitatis, educazione e dignità',body:"<p class='kicker'>Tappa 3</p><h1>Humanitas</h1><p>Il termine non significa semplicemente “mettere l’uomo al centro”. Richiama un ideale educativo: formare una persona capace di parlare, ragionare, giudicare e agire nella vita civile.</p><h3>Gli studia humanitatis</h3><p>Grammatica, retorica, poesia, storia e filosofia morale. Discipline fondate in larga parte sui testi antichi, ma orientate alla formazione dell’uomo presente.</p><h3>Un uomo “integrale”</h3><p>La tua lezione coglie un punto importante: corpo e anima, vita terrena e aspirazione spirituale non devono necessariamente escludersi. Però non esiste un’unica dottrina umanistica: cristianesimo, classicismo, vita civile e ricerca filosofica si combinano in modi diversi.</p><div class='quote'>La vera svolta non è “l’uomo sostituisce Dio”, ma “le capacità umane diventano degne di studio, educazione e fiducia”.</div>"},
{id:'greco',title:'Il ritorno del greco',sub:'Una cultura che riscopre metà delle proprie radici',body:"<p class='kicker'>Tappa 4</p><h1>Il ritorno del greco</h1><p>Per secoli l’Occidente latino aveva avuto un accesso molto limitato alla lingua greca. Nel Quattrocento la situazione cambia rapidamente.</p><div class='timeline'><div class='time-row'><strong>1397</strong><span>Manuele Crisolora insegna greco a Firenze: è un passaggio simbolico decisivo.</span></div><div class='time-row'><strong>1438–1439</strong><span>il Concilio di Ferrara-Firenze porta in Italia importanti dotti bizantini.</span></div><div class='time-row'><strong>1453</strong><span>la caduta di Costantinopoli intensifica gli spostamenti di studiosi e manoscritti verso l’Occidente.</span></div><div class='time-row'><strong>Secondo ’400</strong><span>traduzioni, biblioteche e tipografia moltiplicano la circolazione dei testi.</span></div></div><h3>Perché conta?</h3><p>Platone, storici, filosofi e testi scientifici possono essere letti più direttamente. La cultura europea amplia il proprio archivio e impara sempre più a distinguere fra testo, traduzione e interpretazione.</p><div class='quote'>Il greco non è una moda: cambia ciò che l’Europa può leggere.</div>"},
{id:'potere',title:'Città, corti e potere',sub:'L’intellettuale fra libertà civile e mecenatismo',body:"<p class='kicker'>Tappa 5</p><h1>Città, corti e potere</h1><p>La vecchia lezione insiste giustamente sul mecenatismo. Ma il rapporto tra Umanesimo e potere è più vario: accanto all’umanista di corte esiste l’umanista cancelliere, diplomatico, insegnante, segretario.</p><div class='split'><div class='pole old'><strong>Umanesimo civile</strong><p>Nelle repubbliche, soprattutto a Firenze, il modello romano può alimentare ideali di partecipazione, eloquenza pubblica e libertà politica.</p></div><div class='pole new'><strong>Umanesimo di corte</strong><p>Nelle signorie e negli Stati regionali il principe finanzia biblioteche, artisti e letterati, ricevendone prestigio e strumenti culturali.</p></div></div><h3>La domanda scomoda</h3><p>Il mecenatismo libera l’intellettuale dal bisogno oppure lo lega al potere? La risposta non è unica. Proprio questa ambivalenza prepara molti problemi che ritroveremo in Ariosto, Tasso e Machiavelli.</p>"},
{id:'italia',title:'L’Italia dei centri',sub:'Stati regionali e geografia della cultura',body:"<p class='kicker'>Tappa 6</p><h1>Non una capitale: una rete di centri</h1><p>Nel Quattrocento italiano non nasce uno Stato nazionale. Si consolidano invece grandi Stati regionali e corti che competono anche sul terreno culturale.</p><div class='concept'><div class='panel'><span class='big'>Firenze</span><h3>Medici</h3><p>filologia, platonismo, biblioteche, arti.</p></div><div class='panel'><span class='big'>Milano</span><h3>Visconti / Sforza</h3><p>corte, diplomazia, cultura tecnica e artistica.</p></div><div class='panel'><span class='big'>Ferrara</span><h3>Este</h3><p>cultura cavalleresca, Boiardo, poi Ariosto.</p></div></div><div class='concept'><div class='panel'><span class='big'>Roma</span><h3>Papato</h3><p>biblioteche, curia, classicismo, committenza.</p></div><div class='panel'><span class='big'>Napoli</span><h3>Aragonesi</h3><p>Accademie, latino umanistico, Mediterraneo.</p></div><div class='panel'><span class='big'>Venezia</span><h3>Repubblica</h3><p>editoria, commercio, diffusione europea dei libri.</p></div></div><div class='quote'>L’Umanesimo italiano è policentrico: nasce dalla competizione e dallo scambio fra città, corti, università e biblioteche.</div>"},
{id:'umanesimi',title:'Non un solo Umanesimo',sub:'Filologia, politica, platonismo, cristianesimo',body:"<p class='kicker'>Tappa 7</p><h1>Umanesimi, al plurale</h1><p>La tua vecchia lezione attribuiva al neoplatonismo il “tono dominante”. È una formula troppo larga. Il neoplatonismo fiorentino è importantissimo, ma l’Umanesimo comprende orientamenti diversi.</p><div class='timeline'><div class='time-row'><strong>Filologico</strong><span>Valla e la forza critica della lingua.</span></div><div class='time-row'><strong>Civile</strong><span>Bruni e l’idea che cultura ed eloquenza servano alla vita pubblica.</span></div><div class='time-row'><strong>Platonico</strong><span>Ficino e l’ambiente fiorentino: Platone, anima, amore, armonia.</span></div><div class='time-row'><strong>Dignità</strong><span>Pico della Mirandola: l’uomo come essere aperto, capace di scegliere e formarsi.</span></div><div class='time-row'><strong>Cristiano</strong><span>la riscoperta dei classici convive spesso con la fede, invece di sostituirla.</span></div></div><p>La parola più corretta non è quindi <em>rottura</em>, ma <strong>riconfigurazione</strong>: cambiano gli equilibri fra antico e cristiano, autorità e critica, vita contemplativa e vita civile.</p>"},
{id:'ponte',title:'Verso il Rinascimento',sub:'Boiardo, Poliziano, Bembo come esiti, non come appendice',body:"<p class='kicker'>Tappa 8</p><h1>Verso il Rinascimento</h1><p>Nella tua vecchia lezione Boiardo, Poliziano e Bembo occupavano quasi metà del percorso. Li mantengo, ma cambio la loro funzione: non sono “l’Umanesimo” in blocco; mostrano ciò che la stagione umanistica rende possibile.</p><h3>Boiardo</h3><p>Nella corte estense fonde materia epica e materia amorosa. L’<em>Orlando innamorato</em> porta nel poema cavalleresco il gusto delle corti e una nuova mobilità narrativa.</p><h3>Poliziano</h3><p>È il poeta-filologo per eccellenza della Firenze medicea: classicismo, mito, eleganza formale e cultura di corte convergono nelle <em>Stanze</em> e nell’<em>Orfeo</em>.</p><h3>Bembo</h3><p>È già pienamente dentro il Cinquecento. Nelle <em>Prose della volgar lingua</em> trasforma il lavoro umanistico sui modelli in una proposta normativa per il volgare: Petrarca per la poesia, Boccaccio per la prosa.</p><div class='quote'>Il Quattrocento riscopre e ordina i modelli; il Rinascimento li usa per costruire nuove forme.</div>"}
];

var terms=[
['Humanitas','humanitas','formazione piena dell’essere umano attraverso cultura, parola e vita morale'],
['Studia humanitatis','studia humanitatis','grammatica, retorica, poesia, storia e filosofia morale'],
['Filologia','philologia','studio critico dei testi, delle varianti, della lingua e della loro storia'],
['Ad fontes','ad fontes','ritorno alle fonti: leggere i testi nel modo più diretto e attendibile possibile'],
['Mecenatismo','patronatus','sostegno economico e politico dato da principi e istituzioni ad artisti e studiosi'],
['Umanesimo civile','vita activa','idea che cultura, eloquenza e storia servano anche alla partecipazione politica'],
['Neoplatonismo','Plato renovatus','rilettura di Platone e della tradizione platonica, soprattutto nell’ambiente fiorentino'],
['Volgare','lingua vulgaris','lingua parlata e letteraria non latina, che nel secondo Quattrocento torna a rafforzarsi'],
['Dignità','dignitas hominis','valore attribuito alle capacità dell’uomo di conoscere, scegliere, formarsi e agire']
];

function mapCore(){return "<div class='map'><div class='map-lines'></div><div class='node n1'><strong>Testi</strong>filologia, manoscritti, fonti</div><div class='node n2'><strong>Uomo</strong>educazione, dignità, scelta</div><div class='node n3'><strong>Lingue</strong>latino classico, greco, volgare</div><div class='node n4'><strong>Società</strong>città, corti, potere, mecenati</div><div class='map-center'>UMANESIMO<br><small>nuovo rapporto col passato</small></div></div>";}
function sources(){return "<section class='panel sources'><h3>Da dove parte questa PWA</h3><p>Il percorso nasce dalla vecchia lezione di gbprof <em>L’Umanesimo</em>. Ne conserva la periodizzazione prudente, la centralità della filologia, il tema dell’uomo integrale, il ritorno del greco e il rapporto con le corti. Sono state corrette alcune semplificazioni e una data del Concilio di Ferrara-Firenze; sono stati aggiunti il concetto di <em>studia humanitatis</em>, l’Umanesimo civile, Valla, Pico e la diffusione tipografica come contesto.</p></section>";}
function home(){var pct=Math.round(state.read.length/sections.length*100);var cards=sections.map(function(s,i){return "<a class='lesson' href='#"+s.id+"'><span class='n'>0"+(i+1)+"</span><h3>"+s.title+"</h3><p>"+s.sub+"</p></a>";}).join('');main.innerHTML="<section class='hero'><div class='hero-copy'><span class='chip'>Letteratura · III anno</span><p class='eyebrow'>Quattrocento</p><h1>Imparare di nuovo l’uomo</h1><p class='lead'>L’Umanesimo non mette semplicemente l’uomo al posto di Dio. Cambia il modo di leggere i testi, il passato e le possibilità dell’essere umano.</p><div class='cta'><a class='button' href='#soglia'>Inizia il percorso</a><a class='button secondary' href='#mappe'>Apri le mappe</a></div></div><div class='hero-visual'><img src='data:image/webp;base64,"+window.HUM_COVER+"' alt='Copertina dell’Umanesimo: giovane umanista coronato d’alloro fra libri, globo, statua classica e Firenze'></div></section><div class='wrap'><section class='intro'><div class='panel'><p class='kicker'>La tesi</p><h2>Prima di essere una filosofia, è un nuovo modo di leggere.</h2><p>L’umanista impara a distinguere il testo dalla tradizione che si è accumulata sopra di esso. Da questa pratica nasce una nuova coscienza storica.</p></div><div class='panel'><p class='kicker'>Il tuo percorso</p><h2>"+state.read.length+"/"+sections.length+" tappe completate</h2><div class='progress'><span style='width:"+pct+"%'></span></div><p class='muted'>Il progresso resta salvato su questo dispositivo.</p></div></section><section class='section'><div class='section-head'><p class='kicker'>Percorso</p><h2>Otto tappe: dai manoscritti al Rinascimento</h2></div><div class='route'>"+cards+"</div></section><section class='section'><div class='section-head'><p class='kicker'>Mappa generale</p><h2>Quattro trasformazioni, un solo metodo</h2></div>"+mapCore()+"</section>"+sources()+"</div>";}
function lesson(s){main.innerHTML="<div class='wrap'><div class='content-grid'><article class='article'>"+s.body+"<div class='cta'><a class='button' href='#home'>← Indice</a><a class='button' href='#mappe'>Mappe</a></div></article><aside class='aside'><div class='panel'><p class='kicker'>Tappa</p><h3>"+s.title+"</h3><p>"+s.sub+"</p><button id='mark'>"+(state.read.indexOf(s.id)>=0?"✓ Completata":"Segna come completata")+"</button></div><div class='panel'><strong>Domanda chiave</strong><p>Qui che cosa cambia davvero: il contenuto, il metodo o il rapporto con il passato?</p></div></aside></div></div>";document.getElementById('mark').onclick=function(){var i=state.read.indexOf(s.id);if(i>=0)state.read.splice(i,1);else state.read.push(s.id);save();lesson(s);};}
function showMaps(){main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Mappe concettuali</p><h2>Umanesimo: non uno slogan, ma una rete</h2></section>"+mapCore()+"<section class='section'><div class='concept'><div class='panel'><span class='big'>1</span><h3>Recupera</h3><p>manoscritti, greco, latino classico</p></div><div class='panel'><span class='big'>2</span><h3>Confronta</h3><p>varianti, traduzioni, contesti</p></div><div class='panel'><span class='big'>3</span><h3>Forma</h3><p>l’uomo attraverso gli studia humanitatis</p></div></div></section><section class='section'><div class='panel'><h2>Dal Medioevo al Rinascimento senza salto nel vuoto</h2><div class='timeline'><div class='time-row'><strong>Trecento</strong><span>Petrarca e Boccaccio anticipano nuovi rapporti con i classici e con l’esperienza umana.</span></div><div class='time-row'><strong>Primo ’400</strong><span>latino umanistico, filologia, Umanesimo civile, ritorno del greco.</span></div><div class='time-row'><strong>Metà ’400</strong><span>corti e biblioteche si consolidano; il sapere circola fra più centri.</span></div><div class='time-row'><strong>Secondo ’400</strong><span>tipografia, volgare, platonismo fiorentino, poesia di corte.</span></div><div class='time-row'><strong>Cinquecento</strong><span>le conquiste umanistiche confluiscono nella cultura rinascimentale.</span></div></div></div></section><section class='section'><div class='panel'><h2>La correzione più importante</h2><div class='split'><div class='pole old'><strong>Formula troppo semplice</strong><p>Medioevo = uomo svalutato; Umanesimo = uomo finalmente rivalutato.</p></div><div class='pole new'><strong>Formula più precisa</strong><p>Cambia il modo di pensare la dignità umana, l’educazione, il passato e l’autorità dei testi, dentro una lunga continuità cristiana.</p></div></div></div></section></div>";}
function showTerms(){var cards=terms.map(function(t){return "<article class='term'><div class='latin'>"+t[1]+"</div><h3>"+t[0]+"</h3><p>"+t[2]+"</p></article>";}).join('');main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Vocabolario</p><h2>Nove parole per non ridurre l’Umanesimo a «uomo al centro»</h2></section><div class='terms'>"+cards+"</div></div>";}
var questions=[
["Qual è la tesi centrale della PWA?",["L’Umanesimo sostituisce Dio con l’uomo","L’Umanesimo cambia il rapporto con testi, passato e capacità umane","L’Umanesimo coincide con il Rinascimento"],1],
["Che cosa fa il filologo umanista?",["Accetta la copia più antica senza discuterla","Confronta codici, varianti e contesti","Traduce sempre tutto in volgare"],1],
["Che cosa sono gli studia humanitatis?",["Solo studi religiosi","Grammatica, retorica, poesia, storia e filosofia morale","Matematica, medicina e astronomia soltanto"],1],
["Perché il 1397 è significativo?",["Perché cade Costantinopoli","Per l’insegnamento del greco di Manuele Crisolora a Firenze","Perché nasce Bembo"],1],
["Quale correzione è stata fatta alla vecchia lezione?",["Il Concilio di Ferrara-Firenze è 1438–1439, non 1428–39","La peste è del 1453","Petrarca nasce nel 1397"],0],
["Che cos’è il mecenatismo?",["Una forma di censura religiosa","Il sostegno di poteri e istituzioni a studiosi e artisti","Una scuola filosofica greca"],1],
["Perché è meglio parlare di 'umanesimi' al plurale?",["Perché ogni città parla una lingua diversa","Perché esistono orientamenti filologici, civili, platonici e cristiani diversi","Perché il termine Umanesimo è sbagliato"],1],
["Che funzione hanno Boiardo, Poliziano e Bembo nel percorso?",["Sono presentati come esiti e ponte verso il Rinascimento","Sono i fondatori dell’Umanesimo nel Trecento","Servono solo per imparare tre biografie"],0]
];
function showQuiz(){var html=questions.map(function(q,i){var opts=q[1].map(function(o,j){return "<label class='option'><input type='radio' name='q"+i+"' value='"+j+"' required> "+o+"</label>";}).join('');return "<fieldset><legend>"+(i+1)+". "+q[0]+"</legend>"+opts+"</fieldset>";}).join('');main.innerHTML="<div class='wrap'><section class='section-head'><p class='kicker'>Verifica</p><h2>Hai capito il metodo umanistico?</h2></section><form id='quiz' class='panel quiz'>"+html+"<button>Correggi</button></form><div id='out'></div></div>";document.getElementById('quiz').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),c=0;questions.forEach(function(q,i){if(Number(f.get('q'+i))===q[2])c++;});state.quiz={score:c,date:new Date().toISOString()};save();var msg=c===8?"Hai colto tutti i nessi principali.":c>=5?"La struttura è compresa; ripassa i passaggi meno sicuri.":"Torna alle mappe: distingui prima metodo, idee e contesto.";document.getElementById('out').innerHTML="<div class='result'><h3>"+c+"/8</h3><p>"+msg+"</p></div>";};}
function nav(){var id=location.hash.slice(1)||'home';if(id==='home')home();else if(id==='mappe')showMaps();else if(id==='parole')showTerms();else if(id==='verifica')showQuiz();else{var found=sections.filter(function(s){return s.id===id;})[0];if(found)lesson(found);else home();}window.scrollTo(0,0);main.focus({preventScroll:true});}
document.getElementById('print').onclick=function(){window.print();};
document.getElementById('reset').onclick=function(){if(confirm('Azzero progresso e verifica di Umanesimo su questo dispositivo?')){localStorage.removeItem(KEY);state={read:[],quiz:null};nav();}};
window.addEventListener('hashchange',nav);nav();
if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').then(function(){document.getElementById('offline').textContent='· disponibile offline';}).catch(function(){});}