import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.164.1/build/three.module.js';
import {PointerLockControls} from 'https://cdn.jsdelivr.net/npm/three@0.164.1/examples/jsm/controls/PointerLockControls.js';

const coarse=matchMedia('(pointer:coarse)').matches;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x91a6ae); scene.fog=new THREE.FogExp2(0xa69f8c,.00195);
const camera=new THREE.PerspectiveCamera(coarse?73:69,innerWidth/innerHeight,.06,1100); camera.position.set(0,1.72,142);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setSize(innerWidth,innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,coarse?1.45:2));
renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.05;
document.getElementById('game').appendChild(renderer.domElement);

const hemi=new THREE.HemisphereLight(0xdce7e9,0x554431,1.9); scene.add(hemi);
const sun=new THREE.DirectionalLight(0xffe3b3,3.8); sun.position.set(-150,190,80); sun.castShadow=true;
sun.shadow.mapSize.set(coarse?1024:2048,coarse?1024:2048); sun.shadow.camera.left=-270; sun.shadow.camera.right=270; sun.shadow.camera.top=270; sun.shadow.camera.bottom=-270; sun.shadow.bias=-.0005; scene.add(sun);

function noiseTex(base,a,b,brick=false,scale=4){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle=base;x.fillRect(0,0,512,512);for(let i=0;i<4000;i++){x.globalAlpha=Math.random()*.2;x.fillStyle=Math.random()>.5?a:b;const s=1+Math.random()*4;x.fillRect(Math.random()*512,Math.random()*512,s,s)}if(brick){x.globalAlpha=.22;x.strokeStyle=b;x.lineWidth=2;for(let y=20;y<512;y+=32){x.beginPath();x.moveTo(0,y);x.lineTo(512,y);x.stroke();for(let z=(Math.floor(y/32)%2)*28;z<512;z+=56){x.beginPath();x.moveTo(z,y-32);x.lineTo(z,y);x.stroke()}}}x.globalAlpha=1;const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(scale,scale);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t}
const TX={earth:noiseTex('#877058','#b69a72','#5d4b3b',true,8),plaster:noiseTex('#c9b386','#e9d8ae','#8d7357',false,3),stone:noiseTex('#98856d','#c5ad8c','#665849',true,4),roof:noiseTex('#8b4528','#c26a3e','#552b21',true,5),wood:noiseTex('#563a24','#7d5534','#2f2117',false,3),grass:noiseTex('#5c6d4c','#7f8d64','#3b4b36',false,10)};
const MAT={earth:new THREE.MeshStandardMaterial({map:TX.earth,roughness:1}),plaster:new THREE.MeshStandardMaterial({map:TX.plaster,roughness:.97}),stone:new THREE.MeshStandardMaterial({map:TX.stone,roughness:1}),roof:new THREE.MeshStandardMaterial({map:TX.roof,roughness:.94}),wood:new THREE.MeshStandardMaterial({map:TX.wood,roughness:.92}),dark:new THREE.MeshStandardMaterial({color:0x272520,roughness:.8}),grass:new THREE.MeshStandardMaterial({map:TX.grass,roughness:1}),cloth:new THREE.MeshStandardMaterial({color:0x9a744b,roughness:1,side:THREE.DoubleSide}),metal:new THREE.MeshStandardMaterial({color:0x57534a,roughness:.65,metalness:.35}),water:new THREE.MeshStandardMaterial({color:0x617c85,roughness:.22,metalness:.05})};
const world=new THREE.Group(); scene.add(world); const colliders=[]; const landmarks=[]; const walkers=[];
function shadow(o){o.traverse(v=>{if(v.isMesh){v.castShadow=true;v.receiveShadow=true}})}
function collider(o,p=.04){const b=new THREE.Box3().setFromObject(o);b.expandByScalar(p);colliders.push(b)}
function box(w,h,d,m=MAT.plaster){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);q.castShadow=q.receiveShadow=true;return q}
function roofGeom(w,d,h){const a=w/2,z=d/2;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([-a,0,-z,a,0,-z,0,h,-z,-a,0,z,0,h,z,a,0,z,-a,0,-z,0,h,-z,0,h,z,-a,0,-z,0,h,z,-a,0,z,a,0,-z,a,0,z,0,h,z,a,0,-z,0,h,z,0,h,-z],3));g.computeVertexNormals();return g}
function house(x,z,w=10,d=16,h=7,rot=0,style=0){const g=new THREE.Group();const body=box(w,h,d);body.position.y=h/2;g.add(body);const r=new THREE.Mesh(roofGeom(w+1.2,d+1.2,3.4),MAT.roof);r.position.y=h;g.add(r);const front=d/2+.07;const door=box(1.5,2.8,.16,MAT.wood);door.position.set(0,1.4,front);g.add(door);const floors=h>8?2:1;for(let fy=0;fy<floors;fy++){const yy=4.2+fy*2.6;for(const sx of [-.25,.25]){const win=box(1.15,1.35,.12,MAT.dark);win.position.set(w*sx,yy,front+.04);g.add(win);const sill=box(1.4,.12,.25,MAT.stone);sill.position.set(w*sx,yy-.73,front+.08);g.add(sill)}}if(style===1){for(const sx of [-w*.45,0,w*.45]){const beam=box(.2,h*.5,.18,MAT.wood);beam.position.set(sx,h*.72,front+.08);g.add(beam)}const beam=box(w*.92,.22,.18,MAT.wood);beam.position.set(0,h*.51,front+.08);g.add(beam)}if(style===2){const awn=box(w*.72,.15,2.4,MAT.wood);awn.position.set(0,3.1,front+1.1);awn.rotation.x=-.2;g.add(awn);const cloth=box(w*.68,.08,2.2,MAT.cloth);cloth.position.set(0,3.0,front+1.25);cloth.rotation.x=-.2;g.add(cloth)}g.position.set(x,0,z);g.rotation.y=rot;world.add(g);shadow(g);collider(g);return g}
function church(x,z,s=1,name='Santa Maria Icona Vetere'){const g=new THREE.Group();const nave=box(24*s,15*s,39*s,MAT.stone);nave.position.y=7.5*s;g.add(nave);const rg=new THREE.Mesh(roofGeom(25*s,40*s,7*s),MAT.roof);rg.position.y=15*s;g.add(rg);const tran=box(35*s,13*s,12*s,MAT.stone);tran.position.set(0,6.5*s,-4*s);g.add(tran);const portal=box(4.4*s,6*s,.25,MAT.dark);portal.position.set(0,3*s,19.6*s);g.add(portal);const rose=new THREE.Mesh(new THREE.CylinderGeometry(2.2*s,2.2*s,.25,20),MAT.dark);rose.rotation.x=Math.PI/2;rose.position.set(0,10.7*s,19.7*s);g.add(rose);const tower=box(8*s,28*s,8*s,MAT.stone);tower.position.set(15*s,14*s,-6*s);g.add(tower);const cap=new THREE.Mesh(new THREE.ConeGeometry(5.6*s,8*s,4),MAT.roof);cap.position.set(15*s,32*s,-6*s);cap.rotation.y=Math.PI/4;g.add(cap);g.position.set(x,0,z);world.add(g);shadow(g);collider(g,.2);landmarks.push({name,text:name==='Santa Maria Icona Vetere'?'Fulcro religioso della Foggia medievale. La ricostruzione conserva un carattere romanico-gotico prudente, senza sovrapporre le trasformazioni moderne.':'Chiesa minore del tessuto urbano quattrocentesco.',pos:new THREE.Vector3(x,0,z),r:30});return g}
function palazzo(x,z){const g=new THREE.Group();const main=box(54,12,25,MAT.stone);main.position.y=6;g.add(main);for(const sx of [-20,-10,0,10,20]){const a=box(5,5,.2,MAT.dark);a.position.set(sx,4.5,12.6);g.add(a)}const arch=new THREE.Mesh(new THREE.TorusGeometry(3.7,1.1,8,24,Math.PI),MAT.stone);arch.rotation.z=Math.PI;arch.position.set(0,5.3,12.9);g.add(arch);const gate=box(6,5.2,.2,MAT.dark);gate.position.set(0,2.6,12.7);g.add(gate);g.position.set(x,0,z);world.add(g);shadow(g);collider(g);landmarks.push({name:'Area del palazzo federiciano',text:'Il palazzo di Federico II appartiene al paesaggio storico di Foggia, ma nel Quattrocento il complesso era già segnato da trasformazioni e riusi. Qui è reso come un grande edificio di potere, non come ricostruzione certa della facciata.',pos:new THREE.Vector3(x,0,z),r:35})}
function well(x,z){const g=new THREE.Group();const rim=new THREE.Mesh(new THREE.CylinderGeometry(2.5,2.7,1.3,24),MAT.stone);rim.position.y=.65;g.add(rim);const water=new THREE.Mesh(new THREE.CylinderGeometry(2.0,2.0,.1,24),MAT.water);water.position.y=1.25;g.add(water);for(const sx of [-1.7,1.7]){const p=box(.35,4,.35,MAT.wood);p.position.set(sx,3,0);g.add(p)}const beam=box(4.2,.35,.35,MAT.wood);beam.position.y=5;g.add(beam);g.position.set(x,0,z);world.add(g);shadow(g)}
function tree(x,z,s=1){const g=new THREE.Group();const tr=new THREE.Mesh(new THREE.CylinderGeometry(.35*s,.6*s,4.5*s,8),MAT.wood);tr.position.y=2.25*s;g.add(tr);const leafMat=new THREE.MeshStandardMaterial({color:0x4c633f,roughness:1});for(const [dx,dy,dz,rr] of [[0,5,0,2.4],[-1,4.6,.4,1.8],[1.2,4.8,-.5,1.7]]){const q=new THREE.Mesh(new THREE.IcosahedronGeometry(rr*s,1),leafMat);q.position.set(dx*s,dy*s,dz*s);g.add(q)}g.position.set(x,0,z);world.add(g);shadow(g)}
function stall(x,z,rot=0){const g=new THREE.Group();for(const sx of [-2.5,2.5])for(const zz of [-1.5,1.5]){const p=box(.25,3.2,.25,MAT.wood);p.position.set(sx,1.6,zz);g.add(p)}const top=box(5.8,.12,4,MAT.cloth);top.position.y=3.2;g.add(top);const tbl=box(4.4,.22,1.6,MAT.wood);tbl.position.set(0,1.2,0);g.add(tbl);g.position.set(x,0,z);g.rotation.y=rot;world.add(g);shadow(g);collider(g,.05)}
function cart(x,z,rot=0){const g=new THREE.Group();const bed=box(4,.45,2.2,MAT.wood);bed.position.y=1.4;g.add(bed);for(const sx of [-1.4,1.4])for(const zz of [-1.25,1.25]){const w=new THREE.Mesh(new THREE.TorusGeometry(.75,.16,8,16),MAT.wood);w.rotation.y=Math.PI/2;w.position.set(sx,.8,zz);g.add(w)}const pole=box(.2,.2,4,MAT.wood);pole.position.set(0,1,-3);g.add(pole);g.position.set(x,0,z);g.rotation.y=rot;world.add(g);shadow(g);collider(g,.05)}
function person(x,z,route){const g=new THREE.Group();const tunic=new THREE.Mesh(new THREE.CylinderGeometry(.38,.55,1.35,8),new THREE.MeshStandardMaterial({color:[0x65483a,0x4f5d49,0x726044,0x5c4b64][walkers.length%4],roughness:1}));tunic.position.y=1.05;g.add(tunic);const head=new THREE.Mesh(new THREE.SphereGeometry(.27,10,8),new THREE.MeshStandardMaterial({color:0xb88d68,roughness:1}));head.position.y=1.95;g.add(head);g.position.set(x,0,z);world.add(g);g.userData={route,i:0,t:Math.random()};walkers.push(g)}

// Tavoliere e nucleo urbano
const outer=new THREE.Mesh(new THREE.PlaneGeometry(1000,1000),MAT.grass);outer.rotation.x=-Math.PI/2;outer.receiveShadow=true;world.add(outer);
const city=new THREE.Mesh(new THREE.PlaneGeometry(490,350),MAT.earth);city.rotation.x=-Math.PI/2;city.position.y=.015;city.receiveShadow=true;world.add(city);
// principali assi viari
for(const [x,z,w,d] of [[0,0,28,350],[0,20,490,24],[-105,-25,18,300],[120,35,18,280]]){const r=new THREE.Mesh(new THREE.PlaneGeometry(w,d),new THREE.MeshStandardMaterial({color:0x9f8462,roughness:1}));r.rotation.x=-Math.PI/2;r.position.set(x,.03,z);r.receiveShadow=true;world.add(r)}
// tessuto urbano con vicoli e irregolarità
const blocks=[[-205,-135,5,3],[-145,-135,4,3],[-70,-138,4,3],[55,-138,4,3],[125,-135,4,3],[190,-130,3,3],[-205,-65,5,3],[-145,-62,4,3],[-72,-63,4,3],[55,-62,4,3],[135,-62,4,3],[198,-55,3,3],[-205,20,5,3],[-145,28,4,3],[-72,25,4,3],[65,24,4,3],[140,28,4,3],[205,30,3,3],[-195,95,5,3],[-132,98,4,3],[-60,102,4,3],[55,105,4,3],[125,100,4,3],[190,98,3,3]];
for(const [bx,bz,nx,nz] of blocks){for(let ix=0;ix<nx;ix++)for(let iz=0;iz<nz;iz++){if(Math.random()<.08)continue;const x=bx+ix*12.8+(Math.random()-.5)*1.4,z=bz+iz*18.5+(Math.random()-.5)*1.6;house(x,z,9+Math.random()*2.5,14.5+Math.random()*2.5,6.2+Math.random()*3.6,(Math.random()-.5)*.04,Math.random()<.18?1:(Math.random()<.23?2:0))}}
church(-22,-9,1.05,'Santa Maria Icona Vetere');church(155,80,.72,'Santa Caterina');palazzo(-118,73);
well(96,2); well(-78,-92); for(const p of [[42,6],[52,8],[62,5],[72,9],[42,-6],[54,-7],[66,-5]])stall(p[0],p[1],Math.PI/2); cart(20,38,.2);cart(-35,78,-.4);cart(108,-82,.8);
// orti, alberi e margini urbani
for(let i=0;i<(coarse?100:170);i++){let x,z;if(i<50){x=(Math.random()-.5)*430;z=(Math.random()>.5?1:-1)*(185+Math.random()*120)}else{x=(Math.random()>.5?1:-1)*(255+Math.random()*140);z=(Math.random()-.5)*420}tree(x,z,.7+Math.random()*.65)}
for(const [x,z] of [[-8,78],[25,82],[70,60],[-155,-8],[130,-20]])person(x,z,[[x,z],[x+35,z+10],[x+10,z+35],[x-20,z+5]]);

// landmarks aggiuntivi
landmarks.push({name:'Via Arpi',text:'Uno dei principali assi storici della città. Nel gioco funziona come spina dorsale dell\'abitato e collega le aree religiose, mercantili e residenziali.',pos:new THREE.Vector3(0,0,35),r:22});
landmarks.push({name:'Mercato della città',text:'Foggia quattrocentesca cresce come centro di scambio legato al Tavoliere e alla transumanza. Banchi, carri e botteghe restituiscono questa funzione senza pretendere una ricostruzione puntuale del singolo giorno.',pos:new THREE.Vector3(58,0,3),r:34});
landmarks.push({name:'Dogana e transumanza',text:'Dal 1447 la Regia Dogana della Mena delle Pecore rafforza il ruolo economico di Foggia. Questa zona di traffici evoca il passaggio di uomini, animali e merci verso la città.',pos:new THREE.Vector3(180,0,-115),r:36});

const controls=new PointerLockControls(camera,renderer.domElement);scene.add(controls.getObject());const keys={};
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')inspect()});addEventListener('keyup',e=>keys[e.code]=false);
const enter=document.getElementById('enter');enter.onclick=()=>{document.getElementById('start').style.display='none';if(!coarse)controls.lock()};
controls.addEventListener('unlock',()=>{if(!coarse)document.getElementById('resume').style.display='block'});
document.getElementById('resume').onclick=()=>controls.lock();
document.getElementById('how').onclick=()=>document.getElementById('howBox').hidden=!document.getElementById('howBox').hidden;
let quality='auto';document.getElementById('quality').onclick=()=>{quality=quality==='auto'?'high':quality==='high'?'low':'auto';document.getElementById('quality').textContent='Qualità: '+quality.toUpperCase();applyQuality()};
function applyQuality(){const high=quality==='high'||(quality==='auto'&&!coarse);renderer.setPixelRatio(Math.min(devicePixelRatio,high?2:1.1));sun.shadow.mapSize.set(high?2048:1024,high?2048:1024);sun.shadow.map=null;renderer.shadowMap.needsUpdate=true}
function inspect(){let best=null,dist=1e9;for(const l of landmarks){const d=camera.position.distanceTo(l.pos);if(d<l.r&&d<dist){best=l;dist=d}}if(best){document.getElementById('infoTitle').textContent=best.name;document.getElementById('infoText').textContent=best.text;document.getElementById('info').classList.add('show');setTimeout(()=>document.getElementById('info').classList.remove('show'),9000)}}

// touch controls
let joy={x:0,y:0},run=false,lookId=null,lx=0,ly=0;const base=document.getElementById('joyBase'),knob=document.getElementById('joyKnob'),look=document.getElementById('lookZone');
function joyMove(e){const t=[...e.touches].find(q=>q.target===base||base.contains(q.target));if(!t)return;const r=base.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=t.clientX-cx,dy=t.clientY-cy;const m=Math.hypot(dx,dy)||1,k=Math.min(1,45/m);dx*=k;dy*=k;knob.style.transform=`translate(${dx}px,${dy}px)`;joy.x=dx/45;joy.y=dy/45}
base.addEventListener('touchstart',e=>{e.preventDefault();joyMove(e)},{passive:false});base.addEventListener('touchmove',e=>{e.preventDefault();joyMove(e)},{passive:false});base.addEventListener('touchend',e=>{e.preventDefault();joy={x:0,y:0};knob.style.transform=''},{passive:false});
const runBtn=document.getElementById('runBtn');runBtn.addEventListener('touchstart',e=>{e.preventDefault();run=true},{passive:false});runBtn.addEventListener('touchend',e=>{e.preventDefault();run=false},{passive:false});
look.addEventListener('touchstart',e=>{const t=e.changedTouches[0];lookId=t.identifier;lx=t.clientX;ly=t.clientY},{passive:false});look.addEventListener('touchmove',e=>{const t=[...e.changedTouches].find(q=>q.identifier===lookId);if(!t)return;const dx=t.clientX-lx,dy=t.clientY-ly;lx=t.clientX;ly=t.clientY;camera.rotation.order='YXZ';camera.rotation.y-=dx*.004;camera.rotation.x=Math.max(-1.35,Math.min(1.35,camera.rotation.x-dy*.004))},{passive:false});
document.getElementById('inspectBtn').addEventListener('touchstart',e=>{e.preventDefault();inspect()},{passive:false});

const radius=.48;function collides(p){const pb=new THREE.Box3(new THREE.Vector3(p.x-radius,.1,p.z-radius),new THREE.Vector3(p.x+radius,2.05,p.z+radius));return colliders.some(b=>b.intersectsBox(pb))}
function tryMove(dx,dz){const old=camera.position.clone();camera.position.x+=dx;if(collides(camera.position))camera.position.x=old.x;camera.position.z+=dz;if(collides(camera.position))camera.position.z=old.z}
let bob=0,lastPlace='';const clock=new THREE.Clock();
function animateWalkers(dt){for(const w of walkers){const r=w.userData.route;const target=r[w.userData.i];const v=new THREE.Vector3(target[0]-w.position.x,0,target[1]-w.position.z);if(v.length()<1.2)w.userData.i=(w.userData.i+1)%r.length;else{v.normalize();w.position.addScaledVector(v,dt*1.3);w.rotation.y=Math.atan2(v.x,v.z)}}}
function updatePlace(){let best=null,dist=1e9;for(const l of landmarks){const d=camera.position.distanceTo(l.pos);if(d<l.r&&d<dist){best=l;dist=d}}const el=document.getElementById('place');if(best){el.textContent=best.name+' · premi E / INFO';el.style.opacity=1}else el.style.opacity=0}
function tick(){requestAnimationFrame(tick);const dt=Math.min(clock.getDelta(),.05);const active=coarse?document.getElementById('start').style.display==='none':controls.isLocked;if(active){const f=coarse?-joy.y:((keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0));const s=coarse?joy.x:((keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0));const sprint=coarse?run:(keys.ShiftLeft||keys.ShiftRight);const sp=(sprint?10.5:6.2)*dt;const fw=new THREE.Vector3();camera.getWorldDirection(fw);fw.y=0;fw.normalize();const rt=new THREE.Vector3(-fw.z,0,fw.x);const mv=fw.multiplyScalar(f*sp).add(rt.multiplyScalar(s*sp));tryMove(mv.x,mv.z);if(Math.abs(f)+Math.abs(s)>.08&&!reduced){bob+=dt*(sprint?12:8);camera.position.y=1.72+Math.sin(bob)*.025}else camera.position.y+=(1.72-camera.position.y)*.1;updatePlace()}animateWalkers(dt);renderer.render(scene,camera)}tick();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
